


CREATE FUNCTION [material].[fn_GetMaterialID]
(
    @BARCODE VARCHAR(30),
	@SUPPLIER_CODE VARCHAR(30)
)
RETURNS INT
AS
BEGIN
	DECLARE @ID INT
	SET @ID = (
		  SELECT [MATERIALS].ID 
				FROM [APCSProDB].[TRANS].MATERIALS [MATERIALS]
				INNER JOIN [APCSProDB].[MATERIAL].PRODUCTIONS [PRODUCTIONS]
					ON [MATERIALS].MATERIAL_PRODUCTION_ID = [PRODUCTIONS].ID
				INNER JOIN [APCSProDB].[MATERIAL].SUPPLIERS [SUPPLIERS] 
					ON [PRODUCTIONS].SUPPLIER_CD = [SUPPLIERS].SUPPLIER_CD
				WHERE [MATERIALS].BARCODE = @BARCODE AND [SUPPLIERS].SUPPLIER_CD = @SUPPLIER_CODE
			);
    RETURN @ID

END
