
CREATE Function [material].[fn_GetDayID]
(
    @DATE_VALUE DATE
)
RETURNS INT
AS
BEGIN
	DECLARE @ID INT
	SET @ID = (SELECT [ID] FROM [APCSProDB].[TRANS].[DAYS] WITH (ROWLOCK) WHERE [DATE_VALUE] = @DATE_VALUE);
    RETURN @ID
END
