CREATE Function [material].[fn_space_left]
(
	@TXET_VALUE VARCHAR(1000),
    @SPACE_LENGTH INT
)
RETURNS VARCHAR(1000)
AS
BEGIN 
	RETURN RIGHT(SPACE(@SPACE_LENGTH) + @TXET_VALUE, @SPACE_LENGTH);
END;


