
CREATE Function [material].[fn_space_right]
(
	@TXET_VALUE VARCHAR(1000),
    @SPACE_LENGTH INT
)
RETURNS VARCHAR(1000)
AS
BEGIN 
	RETURN LEFT(@TXET_VALUE + SPACE(@SPACE_LENGTH), @SPACE_LENGTH);
END;
