CREATE PROCEDURE [material].[dashboard_exp_matl]
AS
BEGIN
SELECT PRD.NAME, 
	BARCODE, 
	CONVERT(VARCHAR(20), LIMIT_DATE, 3) AS LIMIT_DATE, 
	CONVERT(VARCHAR(20), EXTENDED_LIMIT_DATE, 3) AS EXTENDED_LIMIT_DATE FROM [APCSProDB].[TRANS].MATERIALS [MAT]
	INNER JOIN [APCSProDB].[MATERIAL].PRODUCTIONS [PRD] ON [MAT].MATERIAL_PRODUCTION_ID = [PRD].ID
	WHERE LIMIT_DATE < GETDATE() + 15 AND (EXTENDED_LIMIT_DATE < GETDATE() + 15 OR EXTENDED_LIMIT_DATE IS NULL)
	AND ISNULL(MATERIAL_STATE, 0) = 0
	AND location_id IN (SELECT id from [APCSProDB].[material].locations where wh_code in ('QI900'))
	ORDER BY LIMIT_DATE
END