CREATE PROCEDURE [ctrlic].[get_id] @TABLENAME VARCHAR(255), @NEWID INT OUTPUT
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
	SET @NEWID = (SELECT [ID] FROM [APCSProDB].man.[NUMBERS] WITH (ROWLOCK) WHERE [NAME] = @TABLENAME);
	IF @NEWID IS NULL
		BEGIN
			SET @NEWID = 1;
			INSERT [APCSProDB].man.[NUMBERS] ([NAME], [ID]) VALUES (@TABLENAME, @NEWID);
		END
	ELSE
		BEGIN
			SET @NEWID = @NEWID + 1;
			UPDATE [APCSProDB].man.[NUMBERS] SET [ID] = @NEWID WHERE [NAME] = @TABLENAME;
		END
COMMIT TRANSACTION;

