-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [cellcon].[sp_get_denpyo_v1]
	-- Add the parameters for the stored procedure here
	@lotNo varchar(10)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT [QR_CODE] AS WSQrcode_332
		  ,[QR_CODE_2] AS WSQrcode_252
		  ,CASE
			WHEN [FORM_NAME_1] IS NOT NULL AND [FORM_NAME_1] != '' THEN [FORM_NAME_1]
			WHEN [FORM_NAME_2] IS NOT NULL AND [FORM_NAME_2] != '' THEN [FORM_NAME_2]
			WHEN [FORM_NAME_3] IS NOT NULL AND [FORM_NAME_3] != '' THEN [FORM_NAME_3]
			WHEN [FORM_NAME_4] IS NOT NULL AND [FORM_NAME_4] != '' THEN [FORM_NAME_4]
			WHEN [FORM_NAME_6] IS NOT NULL AND [FORM_NAME_6] != '' THEN [FORM_NAME_6]
			ELSE NULL
			END AS PackageName
		  ,[PACKAGE_FORM_NAME] AS DeviceName
		  ,[ASSY_MODEL_NAME_1] AS AssyDeviceName
		  ,[FT_MODEL_NAME_1] AS FTDeviceName
		  ,[WARI_INSTRUCT_KBN]
		  ,[FACTORY_CODE]
		  ,[LOT_NO_FOR_PRINT]
		  ,[MANAGE_SECTION_KBN]
		  ,[RESULTS_NO_KBN]
		  ,[CHIP_SIZE]
		  ,[TYPE]
		  ,[SECTION]
		  ,[THROW_DATE_1]
		  ,[ZUBAN_1]
		  ,[ZUBAN_2]
		  ,[MNO_TYPE]		  
		  ,[ASSY_MODEL_NAME_2]		  
		  ,[FORM_NAME_2]
		  ,[THROW_RANK_1]
		  ,[THROW_RANK_2]
		  ,[K_1]
		  ,[K_2]
		  ,[LOT_NO_1]
		  ,[ROHM_CHIP_MODEL_NAME]
		  ,[THROW_PCS]
		  ,[ASSY_SYMBOL_1]
		  ,[ASSY_SYMBOL_2]
		  ,[ASSY_SYMBOL_3]
		  ,[ASSY_SYMBOL_4]
		  ,[ASSY_SYMBOL_5]
		  ,[ASSY_SYMBOL_6]
		  ,[ORDER_NO]
		  ,[INVOICE_NO]
		  ,[ORDER_MODEL_NAME]
		  ,[NOKI]
		  ,[FASET_1]
		  ,[FASET_2]
		  ,[FASET_3]
		  ,[FASET_4]
		  ,[FASET_5]
		  ,[PERETTO_NO_1]
		  ,[PERETTO_NO_2]
		  ,[PERETTO_NO_3]
		  ,[PERETTO_NO_4]
		  ,[PERETTO_NO_5]
		  ,[PERETTO_NO_6]
		  ,[PERETTO_NO_7]
		  ,[PERETTO_NO_8]
		  ,[PERETTO_NO_9]
		  ,[PERETTO_NO_10]
		  ,[PERETTO_NO_11]
		  ,[PERETTO_NO_12]
		  ,[MANU_COND_QUALITY_MATERIAL]
		  ,[SAMPLE_LOT]
		  ,[PROGRAM_NO]
		  ,[BOX_NO_1]
		  ,[BOX_NO_2]
		  ,[HASU_LOT]
		  ,[BOX_NO_3]
		  ,[BOX_NO_4]
		  ,[MESSAGE_1]
		  ,[CODE_NO]
		  ,[FRAME_NAME]
		  ,[FRAME_MAKER_NAME]
		  ,[FRAME_TYPE]
		  ,[MANU_COND_PRIFORM]
		  ,[MANU_COND_CHIP_SIZE_1]
		  ,[MANU_COND_CHIP_SIZE_2]
		  ,[PIN_NO]
		  ,[MANU_COND_GOLD_LINE]
		  ,[RUBBER_NO]
		  ,[MANU_COND_JCR_KBN]
		  ,[RESIN_NAME]
		  ,[RESIN]
		  ,[MANU_COND_1]
		  ,[MANU_COND_2]
		  ,[MANU_COND_3]
		  ,[MANU_COND_4]
		  ,[MANU_COND_5]
		  ,[MANU_COND_6]
		  ,[MANU_COND_7]
		  ,[DC_COND]
		  ,[PAGE_COUNT]
		  ,[PAGE_TITLE]
		  ,[PRODUCT_MANAGE_KBN_1]
		  ,[PRODUCT_MANAGE_KBN_2]
		  ,[DENPYO_SYU]
		  ,[FT_IN_DATE]		  
		  ,[THROW_RANK_3]
		  ,[TP_RANK_1]
		  ,[FORM_NAME_3]
		  ,[LOT_NO_2]
		  ,[MNO1]
		  ,[STANDARD_NUM]
		  ,[SAB_RANK]		  
		  ,[TOMSON_TAKE_NUM_1]
		  ,[TOMSON_TAKE_NUM_2]
		  ,[TOMSON_TAKE_NUM_3]
		  ,[TOMSON_TAKE_NUM_4]
		  ,[TOMSON_NUM_1]
		  ,[TOMSON_NUM_2]
		  ,[TOMSON_NUM_3]
		  ,[TOMSON_NUM_4]
		  ,[LOT_NO_3]
		  ,[KNO]
		  ,[TOMSON_INDICATION]
		  ,[MASK]
		  ,[MNO2]
		  ,[MAKER_NAME]
		  ,[IC_HOKO]
		  ,[B_I_SAMPLE]
		  ,[PACKAGE_TYPE]
		  ,[TUBE_TAKE_NUM]
		  ,[TAPE_NO]
		  ,[REAL_ITEM_NAME]
		  ,[FT_SYMBOL_1]
		  ,[FT_SYMBOL_2]
		  ,[FT_SYMBOL_3]
		  ,[FT_SYMBOL_4]
		  ,[FT_SYMBOL_5]
		  ,[FT_SYMBOL_6]
		  ,[MANU_COMMENT_1]
		  ,[MANU_COMMENT_2]
		  ,[MANU_COMMENT_3]
		  ,[MANU_COMMENT_4]
		  ,[MANU_COMMENT_5]
		  ,[AREA_TIME_RESRV_A1]
		  ,[AREA_TIME_RESRV_A2]
		  ,[AREA_TIME_RESRV_A3]
		  ,[AREA_TIME_RESRV_NS]
		  ,[FT_TESTER_NAME_1]
		  ,[FT_TESTER_NAME_2]
		  ,[FT_TESTER_NAME_3]
		  ,[MESSAGE_2]
		  ,[BAR_LOT_NO_1]
		  ,[LOT_NO_4]
		  ,[BAR_FORM_NAME]
		  ,[FORM_NAME_4]
		  ,[BAR_TP_FORM_1]
		  ,[TP_FORM_1]
		  ,[BAR_ASSY_MODEL_NAME_3]
		  ,[ASSY_MODEL_NAME_4]
		  ,[ASSY_MODEL_NAME_5]
		  ,[FORM_NAME_6]
		  ,[LOT_NO_5]
		  ,[FT_BOX_NO_1]
		  ,[FT_BOX_NO_2]
		  ,[FT_BOX_NO_3]
		  ,[FT_BOX_NO_4]
		  ,[FT_BOX_NO_5]
		  ,[FT_BOX_NO_6]
		  ,[FT_BOX_NO_7]
		  ,[FT_BOX_NO_8]
		  ,[FT_BOX_NO_9]
		  ,[FT_BOX_NO_10]
		  ,[FT_BOX_NO_11]
		  ,[FT_PROCESS_NAME_1]
		  ,[FT_PROCESS_NAME_2]
		  ,[FT_PROCESS_NAME_3]
		  ,[FT_PROCESS_NAME_4]
		  ,[FT_PROCESS_NAME_5]
		  ,[FT_PROCESS_NAME_6]
		  ,[FT_PROCESS_NAME_7]
		  ,[FT_PROCESS_NAME_8]
		  ,[FT_PROCESS_NAME_9]
		  ,[FT_PROCESS_NAME_10]
		  ,[FT_PROCESS_NAME_11]
		  ,[FT_MACHINE_1]
		  ,[FT_MACHINE_2]
		  ,[FT_MACHINE_3]
		  ,[FT_MACHINE_4]
		  ,[FT_MACHINE_5]
		  ,[FT_MACHINE_6]
		  ,[FT_MACHINE_7]
		  ,[FT_MACHINE_8]
		  ,[FT_MACHINE_9]
		  ,[FT_MACHINE_10]
		  ,[FT_MACHINE_11]
		  ,[PASS_TIME_1]
		  ,[PASS_TIME_2]
		  ,[PASS_TIME_3]
		  ,[PASS_TIME_4]
		  ,[PASS_TIME_5]
		  ,[PASS_TIME_6]
		  ,[PASS_TIME_7]
		  ,[TP_PROCESS_NAME_1]
		  ,[TP_PROCESS_NAME_2]
		  ,[TP_PROCESS_NAME_3]
		  ,[TP_PROCESS_NAME_4]
		  ,[TP_PROCESS_NAME_5]
		  ,[TP_PROCESS_NAME_6]
		  ,[TP_PROCESS_NAME_7]
		  ,[TP_RANK_2]
		  ,[DRY_PACKAGE]
		  ,[BAR_LOT_NO_2]
		  ,[LOT_NO_6]
		  ,[BAR_TP_FORM_2]
		  ,[TP_FORM_2]
		  ,[FT_MODEL_NAME_2]
		  ,[FT_MODEL_NAME_3]
		  ,[FT_MODEL_NAME_4]
		  ,[FT_MODEL_NAME_5]
		  ,[FT_MODEL_NAME_6]
		  ,[FT_MODEL_NAME_7]
		  ,[LOT_NO_7]
		  ,[LOT_NO_8]
		  ,[LOT_NO_9]
		  ,[LOT_NO_10]
		  ,[LOT_NO_11]
		  ,[LOT_NO_12]
		  ,[MNO3]
		  ,[MNO4]
		  ,[MNO5]
		  ,[MNO6]
		  ,[MNO7]
		  ,[MNO8]
		  ,[TP_RANK_3]
		  ,[TP_RANK_4]
		  ,[TP_RANK_5]
		  ,[TP_RANK_6]
		  ,[TP_RANK_7]
		  ,[TP_RANK_8]
		  ,[UNION_WORK_DENPYO_SEQ]
		  ,[OUTPUT_END_FLG]
		  ,[OUTPUT_DATE]
		  ,[SEAL_CODE]
		  ,[THROW_DATE_SELECT]
		  ,[TOTAL_PAGE_COUNT]
		  ,[FT_MANU_PROCESS_FLOW_1]
		  ,[FT_MANU_PROCESS_FLOW_2]
		  ,[FT_MANU_PROCESS_FLOW_3]
		  ,[FT_MANU_PROCESS_FLOW_4]
		  ,[PROCESS_POST_CODE]
		  ,[FORWADING_BUNRUI]
		  ,[THROW_RANK_5]
		  ,[MESSAGE_3]
		  ,[MANUAL_TITLE_1]
		  ,[MANUAL_TITLE_2]
		  ,[OYA_LOT_NO]
		  ,[CON_DENPYOU_KBN]
		  ,[CON_DENPYOU_TITLE]		  
		  ,[WB1_EQUIP_NAME]
		  ,[WB1_TIME_LOT]
		  ,[WB2_EQUIP_NAME]
		  ,[WB2_TIME_LOT]
		  ,[MULTI_LABEL_MODEL_NAME_KBN]
		  ,[MULTI_LABEL_MODEL_NAME]
		  ,[RANK_NO]
		  ,[PRN_PROCESS_FLOW_PATTERN_OS]
		  ,[PRN_PROCESS_FLOW_PATTERN_FT]
		  ,[WIRE_NUM_CH]
		  ,[CHIPTRAY_QTY]
		  ,[CHIGIRI_QR1]
		  ,[CHIGIRI_QR2]
		  ,[CHIGIRI_QR3]
		  ,[CHIGIRI_QR4]
		  ,[CHIGIRI_QR5]
		  ,[CHIGIRI_QR6]
		  ,[CHIGIRI_QR7]
		  ,[CHIGIRI_QR8]
		  ,[CHIGIRI_QR9]
		  ,[CREATION_DATE]
		  ,[CREATION_AD_ACCOUNT]
		  ,[CREATION_USER]
		  ,[CREATION_TERMINAL]
		  ,[CREATION_MODULE]
		  ,[UPDATE_DATE]
		  ,[UPDATE_AD_ACCOUNT]
		  ,[UPDATE_USER]
		  ,[UPDATE_TERMINAL]
		  ,[UPDATE_MODULE]
		  ,[DELETE_DATE]
		  ,[DELETE_AD_ACCOUNT]
		  ,[DELETE_USER]
		  ,[DELETE_TERMINAL]
		  ,[DELETE_MODULE]
		  ,[DELETE_FLG]
	FROM APCSDB.dbo.LCQW_UNION_WORK_DENPYO_PRINT
	WHERE (LOT_NO_1 = @lotNo OR
		   LOT_NO_2 = @lotNo OR
		   LOT_NO_3 = @lotNo OR
		   LOT_NO_4 = @lotNo OR
		   LOT_NO_5 = @lotNo OR
		   LOT_NO_6 = @lotNo OR
		   LOT_NO_7 = @lotNo OR
		   LOT_NO_8 = @lotNo OR
		   LOT_NO_9 = @lotNo OR
		   LOT_NO_10 = @lotNo OR
		   LOT_NO_11 = @lotNo OR
		   LOT_NO_12 = @lotNo)
END
