


CREATE PROCEDURE [trans].[report_print_material_label]
@BATCH_ID VARCHAR(MAX)
AS
BEGIN
	SELECT [MATERIALS].[ID]
		  ,[MATERIALS].[BARCODE]
		  ,[MATERIALS].[QUANTITY]
		  ,[PRODUCTIONS].[NAME]
		  ,[CATEGORIES].[NAME] AS [CATEGORY]
		  ,[MATERIALS].lot_no AS [LOT]
		  ,(SELECT DESCRIPTIONS FROM [APCSProDB].[MATERIAL].MATERIAL_CODES MAT_CODES WHERE MAT_CODES.CODE = [PRODUCTIONS].[UNIT_CODE] AND MAT_CODES.[GROUP] = 'package_unit') AS [UNIT]
		  ,(SELECT RECORDED_AT FROM [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL] WHERE ARRIVAL.ID = [MATERIALS].arrival_material_id) AS RECEIVED_DATE
		  ,IsNull([MATERIALS].extended_limit_date, [MATERIALS].limit_date) AS [EXPDATE]
		  ,RIGHT(ISNULL([PARENT].barcode, ''), 3) AS [PARENT]
	  FROM [APCSProDB].[TRANS].[MATERIALS] [MATERIALS]
	  --INNER JOIN [TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL_RECORDS] ON [MATERIALS].[ARRIVAL_MATERIAL_ID] = [ARRIVAL_RECORDS].[ID]
	  INNER JOIN [APCSProDB].[MATERIAL].[PRODUCTIONS] [PRODUCTIONS] ON [MATERIALS].[MATERIAL_PRODUCTION_ID] = [PRODUCTIONS].[ID]
	  INNER JOIN [APCSProDB].[MATERIAL].[CATEGORIES] [CATEGORIES]  ON [CATEGORIES].[ID] = [PRODUCTIONS].[CATEGORY_ID]
	  LEFT JOIN [APCSProDB].[TRANS].[MATERIALS] [PARENT] ON [MATERIALS].parent_material_id = [PARENT].id
	  WHERE [MATERIALS].[ID] IN (SELECT CONVERT(INT, value) FROM STRING_SPLIT(@BATCH_ID,','))
	  ORDER BY [MATERIALS].[ID] ASC
END


