CREATE PROCEDURE [trans].[sp_correct_invalid_invoice]
@INVLALID_INV_ID INT,
@INV_ID INT
AS
BEGIN
	UPDATE [RECORDS] 
			SET [RECORDS].INVOICE_NO = [INVOICES].INVOICENO,
				[RECORDS].[CURRENCY] = [INVOICES].[CURRENCY],
				[RECORDS].[AMOUNT_THB] = [RECORDS].[AMOUNT] * [INVOICES].ORGRECEIVINGUNITPRICE,
				[RECORDS].[UNIT_AMOUNT_THB] = [INVOICES].ORGRECEIVINGUNITPRICE
		FROM [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [RECORDS]
			INNER JOIN [APCSProDB].[TRANS].MATERIALS [MATERIALS] ON [RECORDS].MATERIAL_ID = [MATERIALS].ID
			INNER JOIN [APCSProDB].[MATERIAL].[PRODUCTIONS] [PROD] ON [MATERIALS].MATERIAL_PRODUCTION_ID = [PROD].ID
			INNER JOIN [APCSPRODB].[TRANS].RPT_RCV_INVALID_INVOICE [INVALID] ON [INVALID].PRODUCT_NAME = [PROD].[NAME] 
						AND [RECORDS].PO_NO = [INVALID].PO_NO 
						AND [RECORDS].INVOICE_NO = [INVALID].INVOICE_NO,
			[APCSProDWH].[ONEWORLD].[INVOICE] [INVOICES]
		WHERE [INVALID].ID = @INVLALID_INV_ID AND [INVOICES].ID = @INV_ID
END;

-- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  

