
CREATE PROCEDURE [trans].[sp_delete_receiving]
@ID INT
AS
BEGIN
	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_RECORDS] 
		WHERE MATERIAL_ID IN (SELECT MATERIAL_ID FROM [APCSPRODB].[TRANS].[MATERIAL_RECEIVING_RECORDS] WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID);

	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] 
		WHERE MATERIAL_ID IN (SELECT MATERIAL_ID FROM [APCSPRODB].[TRANS].[MATERIAL_RECEIVING_RECORDS] WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID);

	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_INVENTORY_FILE] 
		WHERE BARCODE IN (SELECT BARCODE FROM [APCSProDB].[TRANS].[MATERIALS] 
			WHERE ID IN (SELECT MATERIAL_ID FROM [APCSPRODB].[TRANS].[MATERIAL_RECEIVING_RECORDS] WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID));

	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_OUTGOING_ITEMS] 
		WHERE MATERIAL_ID IN (SELECT MATERIAL_ID FROM [APCSPRODB].[TRANS].[MATERIAL_RECEIVING_RECORDS] WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID);

	DELETE FROM [APCSProDB].[TRANS].[MATERIALS] 
		WHERE ID IN (SELECT MATERIAL_ID FROM [APCSPRODB].[TRANS].[MATERIAL_RECEIVING_RECORDS] WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID);

	DELETE FROM [APCSPRODB].[TRANS].[MATERIAL_RECEIVING_RECORDS] 
		WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID;

	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_RECEIVING_PROCESS] 
		WHERE ID = @ID;
END