
CREATE PROCEDURE [trans].[sp_delete_material]
@ID INT
AS
BEGIN
	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_RECORDS] WHERE MATERIAL_ID = @ID;
	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] WHERE MATERIAL_ID = @ID;
	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_INVENTORY_FILE] WHERE BARCODE IN (SELECT BARCODE FROM [APCSProDB].[TRANS].[MATERIALS] WHERE ID = @ID);
	DELETE FROM [APCSProDB].[TRANS].[MATERIAL_OUTGOING_ITEMS] WHERE MATERIAL_ID = @ID;
	DELETE FROM [APCSProDB].[TRANS].[MATERIALS] WHERE ID = @ID;
END