



CREATE PROCEDURE [trans].[sp_get_day_id]
@DATE_VALUE Date,
@ID INT OUTPUT
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
	SET @ID = (SELECT [ID] FROM [APCSProDB].[TRANS].[DAYS] WITH (ROWLOCK) WHERE [DATE_VALUE] = @DATE_VALUE);
COMMIT TRANSACTION;
