



CREATE PROCEDURE [trans].[sp_get_sequence_id_v1]
@DAY_ID INT,
@ID INT OUTPUT
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
	
	SET @ID = (SELECT [ID] FROM [APCSProDB].[TRANS].[SEQUENCES] WITH (ROWLOCK) WHERE [DAY_ID] = @DAY_ID);
	IF @ID IS NULL
		BEGIN
			SET @ID = 1;
			INSERT [APCSProDB].[TRANS].[SEQUENCES] ([DAY_ID], [ID]) VALUES (@DAY_ID, @ID);
		END
	ELSE
		BEGIN
			SET @ID = @ID + 1;
			UPDATE [APCSProDB].[TRANS].[SEQUENCES] SET [ID] = @ID WHERE [DAY_ID] = @DAY_ID;
		END
COMMIT TRANSACTION;
