



CREATE PROCEDURE [trans].[sp_get_sequence_id_v2]
@DAY_ID INT,
@ID INT OUTPUT
AS
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--BEGIN TRANSACTION;
	DECLARE @DAY_ID2 INT;
	SET @DAY_ID2 = (SELECT id FROM [APCSProDB].[trans].[days] where [days].[date_value] = (SELECT CONVERT(date, GETDATE())));

	SET @ID = (SELECT [ID] FROM [APCSProDB].[TRANS].[SEQUENCES] WITH (ROWLOCK) WHERE [DAY_ID] =  @DAY_ID2);
	IF @ID IS NULL
		BEGIN
			SET @ID = 1;
			SELECT @ID
			INSERT [APCSProDB].[TRANS].[SEQUENCES] ([DAY_ID], [ID]) VALUES (@DAY_ID2, @ID);
		END
	ELSE
		BEGIN
			SET @ID = @ID + 1;
			SELECT @ID
			UPDATE [APCSProDB].[TRANS].[SEQUENCES] SET [ID] = @ID WHERE [DAY_ID] = @DAY_ID2;
		END
--COMMIT TRANSACTION;
