

CREATE PROCEDURE [trans].[sp_get_number_id_v2] @TABLENAME VARCHAR(255), @NEWID INT OUTPUT
AS
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
--BEGIN TRANSACTION;
	SET @NEWID = (SELECT [ID] FROM [APCSProDB_lsi_110].[TRANS].[NUMBERS] WITH (ROWLOCK) WHERE [NAME] = @TABLENAME);
	IF @NEWID IS NULL
		BEGIN
			SET @NEWID = 1;
			INSERT [APCSProDB_lsi_110].[TRANS].[NUMBERS] ([NAME], [ID]) VALUES (@TABLENAME, @NEWID);
		END
	ELSE
		BEGIN
			SET @NEWID = @NEWID + 1;
			UPDATE [APCSProDB_lsi_110].[TRANS].[NUMBERS] SET [ID] = @NEWID WHERE [NAME] = @TABLENAME;
		END
--COMMIT TRANSACTION;

