CREATE PROCEDURE [TRANS].[sp_insert_pickup_fifo] @BARCODE VARCHAR(50)
AS
BEGIN

DELETE APCSPRODB.[TRANS].[MATERIAL_PICKUP_FILE] WHERE BARCODE = @BARCODE;

INSERT INTO APCSPRODB.[TRANS].[MATERIAL_PICKUP_FILE]
           ([MATERIAL_ID]
           ,[DAY_ID]
           ,[LOCATION_ID]
		   ,[TO_LOCATION_ID]
           ,[WH_CODE]
           ,[PRODUCTION_NAME]
           ,[BARCODE]
           ,[QUANTITY]
           ,[PACK_STD_QTY]
           ,[PACK_UNIT_NAME]
           ,[RECEIVED_DATE]
           ,[EXPIRED_DATE]
           ,[EXTENDED_LIMIT_DATE]
           ,[LOT_NO]
           ,[CREATED_AT])
			SELECT 
				[MTAL].ID,
				[MATERIAL].[FN_GETDAYID](GETDATE()),
				[MTAL].LOCATION_ID,
				[MTAL].LOCATION_ID,
				[LOC].WH_CODE,
				[PROD].NAME,
				[MTAL].BARCODE,
				[MTAL].QUANTITY,
				[PROD].PACK_STD_QTY,
				[PROD].UNIT_CODE,
				[MTAL].CREATED_AT,
				[MTAL].LIMIT_DATE,
				[MTAL].EXTENDED_LIMIT_DATE,
				[MTAL].LOT_NO,
				GETDATE()
				FROM APCSPRODB.TRANS.MATERIALS [MTAL] 
					INNER JOIN APCSPRODB.MATERIAL.LOCATIONS [LOC] ON [MTAL].LOCATION_ID =  [LOC].ID
					INNER JOIN APCSPRODB.MATERIAL.PRODUCTIONS [PROD] ON [MTAL].MATERIAL_PRODUCTION_ID = [PROD].ID
				WHERE [MTAL].BARCODE = @BARCODE;
END

--	EXEC [TRANS].[SP_INSERT_PICKUP_FIFO] '052003060006'