CREATE PROCEDURE [TRANS].[sp_insert_pickup_repack] @BARCODE VARCHAR(50), @QUANTITY INT, @PACK_SIZE INT
AS
BEGIN

DELETE APCSPRODB.[TRANS].[MATERIAL_REPACK_FILE] WHERE BARCODE = @BARCODE;

INSERT INTO APCSPRODB.[TRANS].[MATERIAL_REPACK_FILE]
           ([MATERIAL_ID]
           ,[DAY_ID]
           ,[LOCATION_ID]
		   ,[TO_LOCATION_ID]
           ,[WH_CODE]
           ,[PRODUCTION_NAME]
           ,[BARCODE]
           ,[QUANTITY]
           ,[PACK_STD_QTY]
		   ,[PACK_UNIT_QTY]
		   ,[REPACK_QTY]
           ,[PACK_UNIT_NAME]
           ,[LOT_NO]
           ,[CREATED_AT])
			SELECT 
				[MTAL].ID,
				[MATERIAL].[FN_GETDAYID](GETDATE()),
				[MTAL].LOCATION_ID,
				[MTAL].LOCATION_ID,
				[LOC].WH_CODE,
				[PROD].NAME,
				[MTAL].BARCODE,
				[MTAL].QUANTITY,
				[PROD].PACK_STD_QTY,
				@PACK_SIZE,
				@QUANTITY,
				[UNIT].DESCRIPTIONS,
				[MTAL].LOT_NO,
				GETDATE()
				FROM APCSPRODB.TRANS.MATERIALS [MTAL] 
					INNER JOIN APCSPRODB.MATERIAL.LOCATIONS [LOC] ON [MTAL].LOCATION_ID =  [LOC].ID
					INNER JOIN APCSPRODB.MATERIAL.PRODUCTIONS [PROD] ON [MTAL].MATERIAL_PRODUCTION_ID = [PROD].ID
					INNER JOIN APCSPRODB.MATERIAL.MATERIAL_CODES [UNIT] ON [PROD].UNIT_CODE = [UNIT].CODE 
				WHERE [MTAL].BARCODE = @BARCODE AND UNIT.[GROUP] = 'PACKAGE_UNIT';
END