
CREATE PROCEDURE [trans].[sp_rpt_rcv_daily_balance]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DECLARE @LAST_MONTH AS DATE
	DECLARE @MONTH_BEGIN AS DATE
	DECLARE @LAST_MONTH_INT AS INT

	SET @MONTH_BEGIN = CAST((SELECT CAST(@YEAR_MONTH AS VARCHAR(6)) + '01') AS date);
	SET @LAST_MONTH  = (SELECT DATEADD(m, -1, @MONTH_BEGIN) AS date);
	SET @LAST_MONTH_INT = (SELECT CAST(
		CAST(DATEPART(yyyy, @LAST_MONTH) AS VARCHAR(4)) + 
		REPLACE(STR(DATEPART(MM, @LAST_MONTH), 2), SPACE(1), '0')
		AS INT));
		
		SELECT 
			@YEAR_MONTH AS YEAR_MONTH,
			(SELECT ID FROM [APCSPRODB].[TRANS].[DAYS] WHERE [DATE_VALUE] = @MONTH_BEGIN) AS [DAY_ID],
			LOCATION_ID, 
			[PRODUCT_NAME], 
			(SELECT TOP 1 ID FROM [APCSPRODB].[MATERIAL].[PRODUCTIONS] [PRODUCTIONS] WHERE [PRODUCTIONS].[NAME] = [PRODUCT_NAME]) AS PRODUCT_ID,
			[MONTH_END_QTY] AS [BEGIN_QTY]
			FROM [APCSPRODB].[TRANS].[MATERIAL_LEDGER_HIST] WHERE YEAR_MONTH = @LAST_MONTH_INT AND LOCATION_ID = @LOCATION_ID;

END

--GO
--EXEC [trans].[sp_rpt_rcv_daily_balance] '201904', 2, 1
