CREATE PROCEDURE [trans].[sp_rpt_ledger_transfer_receiving]
@YEAR_MONTH INTEGER,
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	MERGE INTO [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS] WITH (HOLDLOCK) AS TARGET
	USING (SELECT 
		[YEAR_MONTH]
		,[PRODUCT_NAME]
		,SUM([QUANTITY]) AS [QUANTITY]
		,CAST(AVG([TR_UNIT_PRC] / 1000) AS DECIMAL(18, 6)) AS [AVG_UNIT_PRC]
		,0 AS [REC_AMT]
		,[LOCATION] AS WH_CODE
		,@LOCATION_ID AS LOCATION_ID
	FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING] [RECEIVING]
	WHERE [YEAR_MONTH] = @YEAR_MONTH 
		--2019-12-05
		--AND [RECEIVING].[PRODUCT_NAME] IN (SELECT [NAME] FROM [APCSPRODB].[MATERIAL].PRODUCTIONS WHERE CATEGORY_ID = (SELECT ID FROM [APCSPRODB].[MATERIAL].CATEGORIES WHERE SHORT_NAME = '03'))
	GROUP BY [YEAR_MONTH], [PRODUCT_NAME], [LOCATION]) AS SOURCE

    ON TARGET.[YEAR_MONTH] = @YEAR_MONTH
    AND TARGET.[PRODUCT_NAME] = SOURCE.[PRODUCT_NAME]
	WHEN MATCHED THEN 
		UPDATE SET 
			TARGET.REC1_QTY = ISNULL(SOURCE.[QUANTITY], 0), 
			TARGET.REC1_AMT = ISNULL([REC_AMT], 0),
			TARGET.[REC1_AVG_UNIT_PRC] = ISNULL(SOURCE.[AVG_UNIT_PRC], 0)
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (
			[YEAR_MONTH]
			,[PRODUCT_NAME]
			,[MONTH_BEGIN_QTY]
			,[MONTH_BEGIN_AMT]
			,[MONTH_BEGIN_AVG_UNIT_PRC]
			,[REC1_QTY]
			,[REC1_AMT]
			,[REC1_AVG_UNIT_PRC]
			,[WH_CODE]
			,LOCATION_ID
			,[REC2_QTY]
			,[REC2_AMT]
			,[REC3_QTY]
			,[REC3_AMT]
			,[SERV1_QTY]
			,[SERV1_AMT]
			,[SERV2_QTY]
			,[SERV2_AMT]
			,[WH_INV_QTY])
		VALUES (
		SOURCE.[YEAR_MONTH], 
		SOURCE.[PRODUCT_NAME], 
		0,
		0,
		0,
		ISNULL(SOURCE.[QUANTITY], 0), 
		ISNULL(SOURCE.[AVG_UNIT_PRC], 0) * ISNULL(SOURCE.[QUANTITY], 0), 
		ISNULL(SOURCE.[AVG_UNIT_PRC], 0),
		SOURCE.WH_CODE,
		SOURCE.LOCATION_ID,
		0, 0, 0, 0, 0, 0, 0, 0, 0);

		UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS] SET [REC1_AMT] = (
			SELECT SUM(ROUND((([UNIT_AMOUNT_JPY]*[RATE_JPY])+([AMOUNT_USD]*[RATE_USD])+[UNIT_AMOUNT_THB]),2)) 
				FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING_SUMMARY] [SUMMARY] 
					WHERE [SUMMARY].product_name = [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS].product_name 
						and [SUMMARY].year_month = [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS].year_month);

		UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS] SET CATEGORY_SHORT_NAME = 
			(SELECT TOP 1 CATEGORY_ID FROM [APCSPRODB].[MATERIAL].PRODUCTIONS WHERE [NAME] = [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PROCESS].PRODUCT_NAME)
			WHERE CATEGORY_SHORT_NAME IS NULL;
END;


--SELECT * FROM [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]



--SELECT * FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING] WHERE product_name = 'C003-P318' and year_month = '201910'

--SELECT SUM(ROUND((([UNIT_AMOUNT_JPY]*[RATE_JPY])+([AMOUNT_USD]*[RATE_USD])+[UNIT_AMOUNT_THB]),2))
--FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING] WHERE product_name = 'C003-P318' and year_month = '201910'