
CREATE PROCEDURE [trans].[sp_rpt_stockout]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DECLARE @FROM_DATE AS DATE;
	DECLARE @TO_DATE AS DATE;  
	
	SET @FROM_DATE = (SELECT CAST(@YEAR_MONTH + '01' AS DATE));
	SET @TO_DATE = (SELECT DATEADD(d, -1, DATEADD(m, 1, @FROM_DATE)));
	
	SELECT
		[DAYS].DATE_VALUE AS [DATE],
		[PRODUCTIONS].NAME AS [PRODUCT],
		[MATERIALS].BARCODE,
		[FM_LOC].NAME AS [FROM_LOCATION],
		[TO_LOC].NAME AS [TO_LOCATION],
		CASE [OUTGOINGS].STATUS_CODE 
		WHEN 0 THEN 'PENDING'
		WHEN 1 THEN 'RECEIVED'
		END AS [STATUS],
		[USERS].NAME AS [USER]
	  FROM [APCSPRODB].[TRANS].[MATERIAL_OUTGOINGS] [OUTGOINGS]
		INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_OUTGOING_ITEMS] [ITEMS] ON [OUTGOINGS].ID = [ITEMS].MATERIAL_OUTGOINGS_ID
		INNER JOIN [APCSPRODB].[TRANS].DAYS [DAYS] ON [OUTGOINGS].DAY_ID = [DAYS].ID
		INNER JOIN [APCSPRODB].[MATERIAL].LOCATIONS [FM_LOC] ON [OUTGOINGS].FROM_LOCATION_ID = [FM_LOC].ID
		INNER JOIN [APCSPRODB].[MATERIAL].LOCATIONS [TO_LOC] ON [OUTGOINGS].TO_LOCATION_ID = [TO_LOC].ID
		INNER JOIN [APCSPRODB].[MAN].USERS [USERS] ON [OUTGOINGS].PICKING_BY = [USERS].ID
		INNER JOIN [APCSPRODB].[TRANS].MATERIALS [MATERIALS] ON [ITEMS].MATERIAL_ID = [MATERIALS].ID
		INNER JOIN [APCSPRODB].[MATERIAL].PRODUCTIONS [PRODUCTIONS] ON [MATERIALS].MATERIAL_PRODUCTION_ID = [PRODUCTIONS].ID
			WHERE [DAYS].DATE_VALUE BETWEEN @FROM_DATE AND @TO_DATE
		ORDER BY [DAYS].DATE_VALUE DESC, [OUTGOINGS].ID, [ITEMS].ID;
END;

-- EXEC [trans].[[sp_rpt_stockout]] '201908', 2, 1

--select top 100 * from [APCSProDB].[TRANS].oneworld_invoices where specification = 'C004-P54' and po_no = '2936010' order by id desc

--SELECT TOP 100 * FROM [APCSProDB].[TRANS].[ONEWORLD_INVOICES]
