
CREATE PROCEDURE [trans].[sp_rpt_rcv_balance]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DECLARE @LAST_MONTH AS DATE
	DECLARE @MONTH_BEGIN AS DATE
	DECLARE @LAST_MONTH_INT AS INT

	SET @MONTH_BEGIN = CAST((SELECT CAST(@YEAR_MONTH AS VARCHAR(6)) + '01') AS date);
	SET @LAST_MONTH  = (SELECT DATEADD(m, -1, @MONTH_BEGIN) AS date);
	SET @LAST_MONTH_INT = (SELECT CAST(
		CAST(DATEPART(yyyy, @LAST_MONTH) AS VARCHAR(4)) + 
		REPLACE(STR(DATEPART(MM, @LAST_MONTH), 2), SPACE(1), '0')
		AS INT));
		
	DELETE FROM [APCSPRODB].[TRANS].[RPT_RCV_BALANCE];
	
	INSERT [APCSPRODB].[TRANS].[RPT_RCV_BALANCE] (
		  [YEAR_MONTH]
		  ,[LOCATION_ID]
		  ,[DESCRIPTION]
		  ,[PRODUCT_NAME]
		  ,[MATERIAL_PRODUCTION_ID]
		  ,[QUANTITY]
		  ,[DAY_ID])
		SELECT 
			@YEAR_MONTH, 
			LOCATION_ID, 
			'Month Begin', 
			[PRODUCT_NAME], 
			(SELECT TOP 1 ID FROM [APCSPRODB].[MATERIAL].[PRODUCTIONS] [PRODUCTIONS] WHERE [PRODUCTIONS].[NAME] = [PRODUCT_NAME]),
			[MONTH_END_QTY],
			(SELECT ID FROM [APCSPRODB].[TRANS].[DAYS] WHERE [DATE_VALUE] = @MONTH_BEGIN)
			FROM [APCSPRODB].[TRANS].[MATERIAL_LEDGER_HIST] WHERE YEAR_MONTH = @LAST_MONTH_INT AND LOCATION_ID = @LOCATION_ID;

	INSERT [APCSPRODB].[TRANS].[RPT_RCV_BALANCE] (
		  [YEAR_MONTH]
		  ,[LOCATION_ID]
		  ,[DESCRIPTION]
		  ,[PRODUCT_NAME]
		  ,[MATERIAL_PRODUCTION_ID]
		  ,[QUANTITY]
		  ,[LOT_NO]
		  ,[DAY_ID])
		  SELECT
			@YEAR_MONTH,
			LOCATION_ID,
			'Stock In',
			[PRODUCTIONS].[NAME],
			[RECORD].[MATERIAL_PRODUCTION_ID],
			SUM(QUANTITY),
			LOT_NO,
			[RECORD].DAY_ID
		  FROM [APCSPRODB].[TRANS].MATERIAL_RECORDS [RECORD]
			INNER JOIN [APCSPRODB].[MATERIAL].[PRODUCTIONS] [PRODUCTIONS] ON [PRODUCTIONS].[ID] = [RECORD].[MATERIAL_PRODUCTION_ID]
			WHERE RECORD_CLASS = 1 AND LOCATION_ID = @LOCATION_ID AND RECORDED_AT >@MONTH_BEGIN
			GROUP BY LOCATION_ID, [PRODUCTIONS].[NAME], [RECORD].[MATERIAL_PRODUCTION_ID], LOT_NO, [RECORD].DAY_ID


	INSERT [APCSPRODB].[TRANS].[RPT_RCV_BALANCE] (
		  [YEAR_MONTH]
		  ,[LOCATION_ID]
		  ,[DESCRIPTION]
		  ,[PRODUCT_NAME]
		  ,[MATERIAL_PRODUCTION_ID]
		  ,[QUANTITY]
		  ,[LOT_NO]
		  ,[DAY_ID])
		  SELECT
			@YEAR_MONTH,
			LOCATION_ID,
			'Stock Out',
			[PRODUCTIONS].[NAME],
			[RECORD].[MATERIAL_PRODUCTION_ID],
			SUM(QUANTITY) * -1,
			LOT_NO,
			[RECORD].DAY_ID
		  FROM [APCSPRODB].[TRANS].MATERIAL_RECORDS [RECORD]
			INNER JOIN [APCSPRODB].[MATERIAL].[PRODUCTIONS] [PRODUCTIONS] ON [PRODUCTIONS].[ID] = [RECORD].[MATERIAL_PRODUCTION_ID]
			WHERE RECORD_CLASS = 2 AND LOCATION_ID = @LOCATION_ID AND RECORDED_AT >@MONTH_BEGIN
			GROUP BY LOCATION_ID, [PRODUCTIONS].[NAME], [RECORD].[MATERIAL_PRODUCTION_ID], LOT_NO, [RECORD].DAY_ID

		SELECT [YEAR_MONTH]
				,[LOCATION_ID]
				,[DESCRIPTION]
				,[MATERIAL_PRODUCTION_ID]
				,TRIM([PRODUCT_NAME]) AS [PRODUCT_NAME]
				,[INVOICE_NO]
				,[LOT_NO]
				,[QUANTITY]
				,[DAY_ID]
				,[DAYS].DATE_VALUE
			FROM [APCSPRODB].[TRANS].[RPT_RCV_BALANCE] [BALANCE] 
			INNER JOIN [APCSPRODB].[TRANS].[DAYS] [DAYS] ON [BALANCE].DAY_ID = [DAYS].ID
			ORDER BY [PRODUCT_NAME], [DAY_ID]
END

--GO
--EXEC [trans].[sp_rpt_rcv_balance] '201904', 2, 1
