CREATE PROCEDURE [trans].[sp_rpt_invalid_invoice]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DECLARE @FROM_DATE AS DATE;
	DECLARE @TO_DATE AS DATE;  
	
	SET @FROM_DATE = (SELECT CAST(@YEAR_MONTH + '01' AS DATE));
	SET @TO_DATE = (SELECT DATEADD(d, -1, DATEADD(m, 1, @FROM_DATE)));
	
	DELETE FROM [APCSProDB].[TRANS].RPT_RCV_INVALID_INVOICE;

	INSERT [APCSProDB].[TRANS].RPT_RCV_INVALID_INVOICE ([YEAR_MONTH], [PRODUCT_NAME], [PO_NO], [INVOICE_NO], [ARRIVAL_DATE], [QUANTITY])
	SELECT DISTINCT 
		@YEAR_MONTH AS YEAR_MONTH,
		[PROD].[NAME], 
		[RECORDS].PO_NO, 
		[RECORDS].INVOICE_NO,
		CAST([RECORDS].RECORDED_AT AS DATE) AS [DATE], 
		[RECORDS].AMOUNT  AS QUANTITY
		FROM [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [RECORDS]
		INNER JOIN [APCSProDB].[TRANS].MATERIALS [MATERIALS] ON [RECORDS].MATERIAL_ID = [MATERIALS].ID
		INNER JOIN [APCSProDB].[MATERIAL].[PRODUCTIONS] [PROD] ON [MATERIALS].MATERIAL_PRODUCTION_ID = [PROD].ID
		INNER JOIN [APCSProDWH].[ONEWORLD].[INVOICE] [ONEWORLD_INVOICES] 
			ON [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([ONEWORLD_INVOICES].SPECIFICATION, '^a-z0-9') = [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([PROD].[NAME], '^a-z0-9')
				AND (RTRIM([RECORDS].PO_NO) = SUBSTRING(RTRIM([ONEWORLD_INVOICES].PONO), 1, LEN(RTRIM([RECORDS].PO_NO)))
				AND [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([RECORDS].INVOICE_NO, '^a-z0-9') <> [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([ONEWORLD_INVOICES].INVOICENO, '^a-z0-9'))
		WHERE [RECORDS].RECORDED_AT BETWEEN @FROM_DATE AND @TO_DATE 
			AND [ONEWORLD_INVOICES].RECEIVINGDATE > DATEADD(y, -1, @FROM_DATE)
		ORDER BY [PROD].[NAME], [RECORDS].PO_NO, [RECORDS].INVOICE_NO, CAST([RECORDS].RECORDED_AT AS DATE) DESC;

		DELETE [RECORDS] FROM [APCSProDB].[TRANS].RPT_RCV_INVALID_INVOICE [RECORDS]
			INNER JOIN [APCSProDWH].[ONEWORLD].[INVOICE] [ONEWORLD_INVOICES]  ON [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([ONEWORLD_INVOICES].SPECIFICATION, '^a-z0-9') = [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([PRODUCT_NAME], '^a-z0-9')
				AND (RTRIM([RECORDS].PO_NO) = SUBSTRING(RTRIM([ONEWORLD_INVOICES].PONO), 1, LEN(RTRIM([RECORDS].PO_NO)))
				AND [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([RECORDS].INVOICE_NO, '^a-z0-9') = [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([ONEWORLD_INVOICES].INVOICENO, '^a-z0-9'))
			WHERE [ONEWORLD_INVOICES].RECEIVINGDATE BETWEEN DATEADD(y, -1, @FROM_DATE) AND DATEADD(y, 1, @TO_DATE);

		SELECT [YEAR_MONTH], [PRODUCT_NAME] AS [NAME], [PO_NO], [INVOICE_NO], [ARRIVAL_DATE] AS [DATE], [QUANTITY]
			FROM [APCSProDB].[TRANS].RPT_RCV_INVALID_INVOICE;
END;

-- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  

