
CREATE PROCEDURE [trans].[sp_rpt_rcv_frame]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	SELECT 
		[YEAR_MONTH]
		,[PURCHASE_DATE]
		,[INVOICE_NO]
		,[PRODUCT_NAME]
		,[UNIT]
		,[QUANTITY]
		,[UNIT_AMOUNT_JPY]
		,[AMOUNT_USD]
		,[UNIT_AMOUNT_THB]
		,[RATE_USD]
		,[RATE_JPY]
		,ROUND((([UNIT_AMOUNT_JPY]*[RATE_JPY])+([AMOUNT_USD]*[RATE_USD])+[UNIT_AMOUNT_THB]),2) AS TOTAL_AMOUNT
	FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING_SUMMARY]
	WHERE [YEAR_MONTH] = @YEAR_MONTH
	ORDER BY [PRODUCT_NAME];

END

--GO
--EXEC [trans].[sp_rpt_rcv_frame] '201910', 2, 1

--SELECT * FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING] WHERE product_name = 'FES64P-Q21A'