
CREATE PROCEDURE [trans].[sp_rpt_ledger_inprocess]
@YEAR_MONTH INTEGER,
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	UPDATE [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		SET IN_PROCESS_QTY = 
			(SELECT SUM([INPROCESS].QTY)
				FROM [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PRODUCTION] [INPROCESS]
				WHERE [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PROCESS].YEAR_MONTH = [INPROCESS].YEAR_MONTH
					AND [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PROCESS].PRODUCT_NAME = [INPROCESS].PRODUCT_NAME
				)
			WHERE YEAR_MONTH = @YEAR_MONTH AND ISNULL(IN_PROCESS_QTY, 0) = 0
END;
