

CREATE PROCEDURE [trans].[sp_rpt_inventory_sheet]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	SELECT [NO]
		,[YEAR_MONTH]
		,[LOCATION_ID]
		,[NAME]
		,[QUANTITY]
		,[DESCRIPTIONS]
		,[BARCODE]
		,[INV_RPT_NO]
		,[INV_CLASS_NAME]
		,[INV_CLASS]
		,[RACK_NO]
	FROM [APCSProDB].[TRANS].[RPT_INVENTORY_SHEETS]
	WHERE 
	--LOCATION_ID = @LOCATION_ID AND 
	YEAR_MONTH = @YEAR_MONTH
	  ORDER BY [INV_RPT_NO], ISNULL([NAME], 'ZZZZZZZZZZ'), [NO] ASC
END
