
CREATE PROCEDURE [trans].[sp_rpt_ledger_transfer_stock]
@YEAR_MONTH INTEGER,
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DECLARE @_NAME NVARCHAR(50)
	DECLARE @_QUANTITY DECIMAL(18, 6)
	DECLARE DB_CURSOR CURSOR LOCAL FAST_FORWARD FOR
		SELECT [NAME], SUM(ISNULL([QUANTITY], 0)) AS [QUANTITY] 
		FROM [APCSProDB].TRANS.RPT_INVENTORY_SHEETS [SHEET] WHERE [NAME] IS NOT NULL AND [SHEET].YEAR_MONTH = @YEAR_MONTH
		AND [SHEET].LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))
		GROUP BY [NAME];
	
		OPEN DB_CURSOR  
		FETCH NEXT FROM DB_CURSOR INTO @_NAME, @_QUANTITY
			WHILE @@FETCH_STATUS = 0  
			BEGIN
				IF EXISTS(SELECT 1 FROM [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS] WHERE [PRODUCT_NAME] = @_NAME)
					UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS] SET WH_INV_QTY = @_QUANTITY WHERE [PRODUCT_NAME] = @_NAME;
				ELSE
					INSERT INTO [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PROCESS]
								   ([LOCATION_ID]
								   ,[WH_CODE]
								   ,[CATEGORY_SHORT_NAME]
								   ,[PRODUCT_NAME]
								   ,[YEAR_MONTH]
								   ,[WH_INV_QTY]
								   ,[WH_INV_AMT]
								   ,[CREATED_AT]
								   ,[CREATED_BY])
							 VALUES
								   (@LOCATION_ID
								   ,(SELECT WH_CODE FROM [APCSPRODB].MATERIAL.LOCATIONS WHERE ID = @LOCATION_ID)
								   ,(SELECT TOP 1 CATEGORY_ID FROM [APCSPRODB].MATERIAL.PRODUCTIONS WHERE [NAME] = @_NAME)
								   ,@_NAME
								   ,@YEAR_MONTH
								   ,@_QUANTITY
								   ,0
								   ,GETDATE()
								   ,@USER_ID)
				FETCH NEXT FROM DB_CURSOR INTO @_NAME, @_QUANTITY
			END
		CLOSE DB_CURSOR  
		DEALLOCATE DB_CURSOR 
END;

