

CREATE PROCEDURE [trans].[sp_rpt_rcv_submatl_process]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DECLARE @FROM_DATE AS DATE;
	DECLARE @TO_DATE AS DATE;
	
	SET @FROM_DATE = (SELECT CAST(@YEAR_MONTH + '01' AS DATE));
	SET @TO_DATE = (SELECT DATEADD(d, -1, DATEADD(m, 1, @FROM_DATE)));

	DELETE FROM [TRANS].[RPT_SUB_MATERIAL_RECEIVING] WHERE [YEAR_MONTH] = @YEAR_MONTH;

	INSERT INTO [TRANS].[RPT_SUB_MATERIAL_RECEIVING]
           ([YEAR_MONTH]
           ,[PRODUCT_NAME]
           ,[ITEM]
           ,[PROCESS]
           ,[QUANTITY]
           ,[UNIT]
           ,[AMOUNT]
           ,[CREATED_AT]
           ,[CREATED_BY])
	SELECT
		@YEAR_MONTH,
		[PROD].[NAME],
		[PROCESS].[Group_Item], 
		[PROCESS].[PROCESS], 
		[RECORDS].QUANTITY,
		[UNIT].DESCRIPTIONS,
		[ARRIVAL].AMOUNT_THB,
		GETDATE(),
		@USER_ID
	FROM [TRANS].[MATERIAL_RECORDS] [RECORDS]
		INNER JOIN [TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL] ON [RECORDS].MATERIAL_ID = [ARRIVAL].[MATERIAL_ID]
		INNER JOIN [TRANS].[MATERIALS] [MATL] ON [RECORDS].MATERIAL_ID = [MATL].ID
		INNER JOIN [MATERIAL].[PRODUCTIONS] [PROD] ON [RECORDS].MATERIAL_PRODUCTION_ID = [PROD].ID
		LEFT JOIN [MATERIAL].[PURCHASE_ORDER_ITEMS] [CONVERSION] ON [PROD].[ID] = [CONVERSION].[MATERIAL_ID]
		LEFT JOIN [MATERIAL].[PRODUCTION_PROCESSES] [PROCESS] ON [CONVERSION].[SPECIFICATION] = [PROCESS].[ITEM]
		INNER JOIN [MATERIAL].[MATERIAL_CODES] [UNIT] ON [PROD].UNIT_CODE = [UNIT].CODE AND [UNIT].[GROUP] = 'package_unit'
		INNER JOIN [TRANS].[DAYS] [DAYS] ON [DAYS].ID = [RECORDS].DAY_ID
		WHERE [RECORDS].RECORD_CLASS = '0' 
		AND [RECORDS].location_id = @LOCATION_ID 
		--AND [PROD].CATEGORY_ID = (SELECT TOP 1 ID FROM [Material].[CATEGORIES] WHERE SHORT_NAME = '10' )
		AND [DAYS].DATE_VALUE BETWEEN @FROM_DATE AND @TO_DATE
		ORDER BY [RECORDS].ID;
END


