


CREATE PROCEDURE [trans].[sp_rpt_data_interface_2]
@FILE_DATE DATE,
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @WRITE_TIME DATETIME
	DECLARE @DATE_FORMAT VARCHAR(255)
	DECLARE @_NO INT
	DECLARE @_BARCODE VARCHAR(12)
	DECLARE @_LOCATION_ID INT
	DECLARE @_PROD_NAME CHAR(20)
	DECLARE @_QUANTITY DECIMAL(18, 6)
	DECLARE @_ARRIVAL_LOCATION CHAR(5)
	DECLARE @_FROM_LOCATION CHAR(5)
	DECLARE @_TO_LOCATION CHAR(5)
	DECLARE @_SUPPLIER_CD CHAR(5)
	DECLARE @_CATE_CODE CHAR(2)
	DECLARE @_IN_DATE DATETIME
	DECLARE @_RECORD_CLASS INT
	DECLARE @_PO_NO CHAR(10)
	DECLARE @_INV_NO CHAR(10)
	DECLARE @DAY_ID INT

	SET @WRITE_TIME = GETDATE()
	SET @DATE_FORMAT = CONVERT(VARCHAR(8), GETDATE(), 112) + REPLACE(CONVERT(VARCHAR(5), GETDATE(), 114), ':', '')
	SET @DAY_ID = [material].fn_GetDayID(@FILE_DATE)
	SET @_NO = 1;
	DELETE FROM [APCSPRODB].[TRANS].[ADM00001] WHERE DATEDIFF(d, MAKDT, @FILE_DATE) = 0;

-- ************** FUK5 ************** --
	DECLARE DB_CURSOR_FUK5 CURSOR LOCAL FAST_FORWARD FOR
		SELECT
			[MATL].BARCODE, 
			[LOC].WH_CODE AS ARRIVAL_LOCATION, 
			[CATE].SHORT_NAME AS CATE_CODE, 
			[PROD].NAME AS PROD_NAME,
			[MATL].QUANTITY,
			[PROD].SUPPLIER_CD,
			[ARRIVAL].RECORDED_AT AS IN_DATE
			FROM [APCSPRODB].[TRANS].[MATERIALS] [MATL] 
				INNER JOIN [APCSPRODB].MATERIAL.PRODUCTIONS [PROD] ON [MATL].MATERIAL_PRODUCTION_ID = [PROD].ID
				INNER JOIN [APCSPRODB].MATERIAL.CATEGORIES [CATE] ON [PROD].CATEGORY_ID = [CATE].ID
				INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL] ON [MATL].ID = [ARRIVAL].MATERIAL_ID 
				INNER JOIN [APCSPRODB].MATERIAL.LOCATIONS [LOC] ON [MATL].LOCATION_ID = [LOC].ID
			ORDER BY [MATL].BARCODE;

	OPEN DB_CURSOR_FUK5  
	FETCH NEXT FROM DB_CURSOR_FUK5 INTO @_BARCODE, @_ARRIVAL_LOCATION, @_CATE_CODE, @_PROD_NAME, @_QUANTITY, @_SUPPLIER_CD, @_IN_DATE;
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @_NO = 1
			BEGIN
				-- FUK5 HEADER
				INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
				VALUES(
					@FILE_DATE
					,@_NO
					,'FUK5'
					,'GESGEIS1.000ZZROHM0024'+ SPACE(7) +'ZZROHM0011'+ SPACE(7) + RIGHT(@DATE_FORMAT, 10) + [material].[fn_space_right]('FUK5', 9) + 'JST' + SPACE(12)
					,0
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,@WRITE_TIME
					,@USER_ID
					,'PC001'
					,0
					,@WRITE_TIME
					,SPACE(1)
					,SPACE(1)
				);
			END;

			IF @_NO > 1
			BEGIN
				-- FUK5 CONTENT
				INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
				VALUES(
					@FILE_DATE
					,@_NO
					,'FUK5'
					,[material].[fn_space_right](
							@_CATE_CODE + 
							@_ARRIVAL_LOCATION + 
							[material].[fn_space_right](@_PROD_NAME, 20) + 
							FORMAT(@_QUANTITY * 100, '00000000000') + 
							[material].[fn_space_right](@_SUPPLIER_CD, 5) + 
							[material].[fn_space_right](@_BARCODE, 12) + 
							CONVERT(VARCHAR(8), @_IN_DATE, 112)
						, 80)
					,0
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,@WRITE_TIME
					,@USER_ID
					,'PC001'
					,0
					,@WRITE_TIME
					,SPACE(1)
					,SPACE(1)
				);
			END;
			SET @_NO = @_NO + 1;
			FETCH NEXT FROM DB_CURSOR_FUK5 INTO @_BARCODE, @_ARRIVAL_LOCATION, @_CATE_CODE, @_PROD_NAME, @_QUANTITY, @_SUPPLIER_CD, @_IN_DATE;
		END
	CLOSE DB_CURSOR_FUK5  
	DEALLOCATE DB_CURSOR_FUK5;

	-- FUK5 FOOTER
	INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
	VALUES(
		@FILE_DATE
		,@_NO -- COUNT REC
		,'FUK5'
		,'GEE'+ FORMAT(@_NO, '000000') + [material].[fn_space_right]('FUK5', 9) + SPACE(62)
		,0
		,@FILE_DATE
		,@USER_ID
		,'PC001'
		,@WRITE_TIME
		,@USER_ID
		,'PC001'
		,0
		,@WRITE_TIME
		,SPACE(1)
		,SPACE(1)
	);
-- ************** FUK5 ************** --

-- ************** MAIO ************** --
	DECLARE @_CATE_ID INT
	DECLARE @_SEQ_NO INT

	SET @_SEQ_NO = 1
	DECLARE DB_CURSOR_MAIO_CATE CURSOR LOCAL FAST_FORWARD FOR
		SELECT ID FROM [APCSPRODB].MATERIAL.CATEGORIES [CATE]
		OPEN DB_CURSOR_MAIO_CATE 
		FETCH NEXT FROM DB_CURSOR_MAIO_CATE INTO @_CATE_ID
		WHILE @@FETCH_STATUS = 0
		BEGIN --DB_CURSOR_MAIO_CATE 
			SET @_NO = 1;
			DECLARE DB_CURSOR_MAIO CURSOR LOCAL FAST_FORWARD FOR
				SELECT 
					[MATL].BARCODE, 
					[LOC].WH_CODE AS ARRIVAL_LOCATION, 
					[CATE].SHORT_NAME AS CATE_CODE, 
					[PROD].NAME AS PROD_NAME,
					[RECORD].QUANTITY,
					[PROD].SUPPLIER_CD,
					[RECORD].RECORDED_AT AS IN_DATE,
					CASE [RECORD].RECORD_CLASS
						WHEN 1 THEN 11 -- IN
						WHEN 2 THEN 15 -- OUT
					END AS RECORD_CLASS,
					[ARRIVAL].PO_NO,
					[ARRIVAL].INVOICE_NO
					FROM [APCSPRODB].[TRANS].[MATERIALS] [MATL] 
						INNER JOIN [APCSPRODB].MATERIAL.PRODUCTIONS [PROD] ON [MATL].MATERIAL_PRODUCTION_ID = [PROD].ID
						INNER JOIN [APCSPRODB].MATERIAL.CATEGORIES [CATE] ON [PROD].CATEGORY_ID = [CATE].ID
						INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_RECORDS] [RECORD] ON [MATL].ID = [RECORD].MATERIAL_ID 
						INNER JOIN [APCSPRODB].MATERIAL.LOCATIONS [LOC] ON [RECORD].LOCATION_ID = [LOC].ID
						LEFT JOIN [APCSPRODB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL] ON [MATL].ID = [ARRIVAL].MATERIAL_ID
						WHERE [RECORD].record_class IN (1, 2)
						AND [LOC].wh_code IN ('QI900', 'QI999', 'QI000')
						AND [RECORD].day_id = @DAY_ID
						AND [CATE].ID = @_CATE_ID
					ORDER BY [MATL].BARCODE;

			OPEN DB_CURSOR_MAIO 
			FETCH NEXT FROM DB_CURSOR_MAIO INTO @_BARCODE, @_ARRIVAL_LOCATION, @_CATE_CODE, @_PROD_NAME, @_QUANTITY, @_SUPPLIER_CD, @_IN_DATE, @_RECORD_CLASS, @_PO_NO, @_INV_NO;
			WHILE @@FETCH_STATUS = 0
				BEGIN
					IF @_NO = 1
					BEGIN
						-- MAIO HEADER
						INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
						VALUES(
							@FILE_DATE
							,@_SEQ_NO
							,'MAIO'
							,'GESGEIS1.000ZZROHM0024'+ SPACE(7) +'ZZROHM0010'+ SPACE(7) + RIGHT(@DATE_FORMAT, 10) + [material].[fn_space_right]('MAIO', 9) + 'JST' + SPACE(12)
							,0
							,@FILE_DATE
							,@USER_ID
							,'PC001'
							,@WRITE_TIME
							,@USER_ID
							,'PC001'
							,0
							,@WRITE_TIME
							,SPACE(1)
							,SPACE(1)
						);
					END;

					IF @_NO > 1
					BEGIN
						-- MAIO CONTENT / 1
						INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
						VALUES(
							@FILE_DATE
							,@_SEQ_NO
							,'MAIO'
							,	CAST(@_RECORD_CLASS AS CHAR(2)) +
								RIGHT(CONVERT(VARCHAR(8), @FILE_DATE, 112), 6) +
								[material].[fn_space_right](@_ARRIVAL_LOCATION, 5) +
								[material].[fn_space_right](@_ARRIVAL_LOCATION, 5) +
								[material].[fn_space_right](@_PROD_NAME, 20) + 
								FORMAT(@_QUANTITY * 100, '00000000000') +
								'00000' + 
								'0' + -- RED BLOCK
								[material].[fn_space_right](@_INV_NO, 10) + 
								[material].[fn_space_right](@_PO_NO, 10) + 
								SPACE(2) + 
								SPACE(3) 
							,0
							,@FILE_DATE
							,@USER_ID
							,'PC001'
							,@WRITE_TIME
							,@USER_ID
							,'PC001'
							,0
							,@WRITE_TIME
							,SPACE(1)
							,SPACE(1)
						);
					END;
					SET @_NO = @_NO + 1;
					SET @_SEQ_NO = @_SEQ_NO + 1
					FETCH NEXT FROM DB_CURSOR_MAIO INTO @_BARCODE, @_ARRIVAL_LOCATION, @_CATE_CODE, @_PROD_NAME, @_QUANTITY, @_SUPPLIER_CD, @_IN_DATE, @_RECORD_CLASS, @_PO_NO, @_INV_NO;
				END
			CLOSE DB_CURSOR_MAIO  
			DEALLOCATE DB_CURSOR_MAIO;

			-- MAIO FOOTER
			IF @_NO > 1 -- HAS RECORDS
				INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
				VALUES(
					@FILE_DATE
					,@_SEQ_NO
					,'MAIO'
					,'GEE'+ FORMAT(@_NO, '000000') + [material].[fn_space_right]('MAIO', 9) + SPACE(62)
					,0
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,@WRITE_TIME
					,@USER_ID
					,'PC001'
					,0
					,@WRITE_TIME
					,SPACE(1)
					,SPACE(1)
				);
			ELSE
				SET @_SEQ_NO = @_SEQ_NO - 1

			SET @_SEQ_NO = @_SEQ_NO + 1
	FETCH NEXT FROM DB_CURSOR_MAIO_CATE INTO @_CATE_ID
	END --DB_CURSOR_MAIO_CATE

-- ************** MAIO ************** --

-- ************** FUK4 ************** --
	DECLARE @_QC_STATE AS INT

	SET @_NO = 1;
	DECLARE DB_CURSOR_FUK4 CURSOR LOCAL FAST_FORWARD FOR
		SELECT 
			[MATL].BARCODE, 
			[LOCATIONS].WH_CODE AS ARRIVAL_LOCATION, 
			[CATE].SHORT_NAME AS CATE_CODE, 
			[PROD].NAME AS PROD_NAME,
			[MATL].QUANTITY,
			[PROD].SUPPLIER_CD,
			[RECORD].RECORDED_AT AS IN_DATE,
			CASE [RECORD].RECORD_CLASS
				WHEN 1 THEN 11 -- IN
				WHEN 2 THEN 15 -- OUT
				ELSE 99
			END AS RECORD_CLASS,
			[ARRIVAL].PO_NO,
			[ARRIVAL].INVOICE_NO,
			[MATL].QC_STATE,
			[FROM_LOCATIONS].WH_CODE,
			[TO_LOCATIONS].WH_CODE
			FROM [APCSPRODB].[TRANS].[MATERIALS] [MATL] 
				INNER JOIN [APCSPRODB].MATERIAL.PRODUCTIONS [PROD] ON [MATL].MATERIAL_PRODUCTION_ID = [PROD].ID
				INNER JOIN [APCSPRODB].MATERIAL.CATEGORIES [CATE] ON [PROD].CATEGORY_ID = [CATE].ID
				INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_RECORDS] [RECORD] ON [MATL].ID = [RECORD].MATERIAL_ID
				INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL] ON [MATL].ID = [ARRIVAL].MATERIAL_ID  
				INNER JOIN [APCSPRODB].MATERIAL.LOCATIONS [LOCATIONS] ON [ARRIVAL].LOCATION_ID = [LOCATIONS].ID
				INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_OUTGOING_ITEMS] [OUTGOINGS_ITEM] ON [RECORD].ID = [OUTGOINGS_ITEM].RECORD_ID
				INNER JOIN [APCSPRODB].[TRANS].[MATERIAL_OUTGOINGS] [OUTGOINGS] ON [OUTGOINGS].ID = [OUTGOINGS_ITEM].MATERIAL_OUTGOINGS_ID
				INNER JOIN [APCSPRODB].MATERIAL.LOCATIONS [FROM_LOCATIONS] ON [OUTGOINGS].FROM_LOCATION_ID = [FROM_LOCATIONS].ID
				INNER JOIN [APCSPRODB].MATERIAL.LOCATIONS [TO_LOCATIONS] ON [OUTGOINGS].TO_LOCATION_ID = [TO_LOCATIONS].ID
			WHERE [RECORD].RECORD_CLASS <> 0 -- REGISTER
				AND [RECORD].RECORD_CLASS <> 3 -- STOCK
				AND [RECORD].DAY_ID = @DAY_ID
			ORDER BY [MATL].BARCODE;

	OPEN DB_CURSOR_FUK4  
	FETCH NEXT FROM DB_CURSOR_FUK4 INTO @_BARCODE, @_ARRIVAL_LOCATION, @_CATE_CODE, @_PROD_NAME, @_QUANTITY, @_SUPPLIER_CD, @_IN_DATE, @_RECORD_CLASS, @_PO_NO, @_INV_NO, @_QC_STATE, @_FROM_LOCATION, @_TO_LOCATION;
	WHILE @@FETCH_STATUS = 0
		BEGIN
			IF @_NO = 1
			BEGIN
				-- FUK4 HEADER
				INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
				VALUES(
					@FILE_DATE
					,@_NO
					,'FUK4'
					,'GESGEIS1.000ZZROHM0024'+ SPACE(7) +'ZZROHM0011'+ SPACE(7) + RIGHT(@DATE_FORMAT, 10) + [material].[fn_space_right]('FUK4', 9) + 'JST' + SPACE(12)
					,0
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,@WRITE_TIME
					,@USER_ID
					,'PC001'
					,0
					,@WRITE_TIME
					,SPACE(1)
					,SPACE(1)
				);
			END;

			IF @_NO > 1
			BEGIN
				-- FUK4 CONTENT / 1
				INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
				VALUES(
					@FILE_DATE
					,@_NO
					,'FUK4'
					,'01' + 
						CAST(@_RECORD_CLASS AS CHAR(2)) + 
						@_CATE_CODE + 
						[material].[fn_space_right](@_ARRIVAL_LOCATION, 5) + -- IN DEP
						[material].[fn_space_right](@_FROM_LOCATION, 5) + -- ISSUE
						[material].[fn_space_right](@_TO_LOCATION, 5) + -- REC DEP
						[material].[fn_space_right](@_PROD_NAME, 20) + 
						FORMAT(@_QUANTITY * 100, '00000000000') + 
						'1' +  -- RED_BLK_CLS
						'1' + -- COM VALUE
						'G' + 
						ISNULL(@_PO_NO, SPACE(10)) + 
						ISNULL(@_INV_NO, SPACE(10)) +
						SPACE(3) + 
						SPACE(1) + 
						SPACE(1)
					,0
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,0
					,@FILE_DATE
					,SPACE(1)
					,SPACE(1)
				);

				SET @_NO = @_NO + 1;

				-- FUK4 CONTENT / 2
				INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
				VALUES(
					@FILE_DATE
					,@_NO
					,'FUK4'
					,CAST('02' + CONVERT(VARCHAR(8), @_IN_DATE, 112) + CONVERT(VARCHAR(8), @_IN_DATE, 112) + SPACE(62) AS CHAR(80))
					,0
					,@FILE_DATE
					,@USER_ID
					,'PC001'
					,@WRITE_TIME
					,@USER_ID
					,'PC001'
					,0
					,@WRITE_TIME
					,SPACE(1)
					,SPACE(1)
				);
				--,@_CATE_CODE + @_ARRIVAL_LOCATION + @_PROD_NAME + FORMAT(@_QUANTITY * 100, '00000000000') + @_SUPPLIER_CD + @_BARCODE + CONVERT(VARCHAR(8), @_IN_DATE, 112)
			END;
			SET @_NO = @_NO + 1;
			FETCH NEXT FROM DB_CURSOR_FUK4 INTO @_BARCODE, @_ARRIVAL_LOCATION, @_CATE_CODE, @_PROD_NAME, @_QUANTITY, @_SUPPLIER_CD, @_IN_DATE, @_RECORD_CLASS, @_PO_NO, @_INV_NO, @_QC_STATE, @_FROM_LOCATION, @_TO_LOCATION;
		END
	CLOSE DB_CURSOR_FUK4  
	DEALLOCATE DB_CURSOR_FUK4;

	-- FUK4 FOOTER
	INSERT [APCSPRODB].[TRANS].[ADM00001] ([WRITETIME] ,[SEQNO6] ,[ROVANSFILE] ,[ROVANSDATA] ,[SENDENDFL] ,[MAKDT] ,[MAKP] ,[MAKC] ,[UPDDT] ,[UPDP] ,[UPDC] ,[DELF] ,[DELDT] ,[DELP] ,[DELC])
	VALUES(
		@FILE_DATE
		,@_NO
		,'FUK4'
		,'GEE'+ FORMAT(@_NO, '000000') +'FUK4'
		,0
		,@FILE_DATE
		,@USER_ID
		,'PC001'
		,@WRITE_TIME
		,@USER_ID
		,'PC001'
		,0
		,@WRITE_TIME
		,SPACE(1)
		,SPACE(1)
	);
-- ************** FUK4 ************** --

	SET NOCOUNT OFF
END;



--	EXEC [trans].[sp_rpt_data_interface_2] '2019-10-03 01:30:40.853', 2, 1

--SELECT * FROM [APCSPRODB].[TRANS].[ADM00001] WHERE rovansfile = 'MAIO' ORDER BY UPDDT DESC