CREATE PROCEDURE [trans].[sp_rpt_rcv_frame_process]
@YEAR_MONTH VARCHAR(8),
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	DELETE FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING]
	
	DECLARE @USD_RATE AS DECIMAL(16, 6);
	DECLARE @JPY_RATE AS DECIMAL(16, 6);

	--DECLARE @FROM_DATE AS DATETIME; 
	--DECLARE @TO_DATE AS DATETIME; 
	DECLARE @FROM_DATE AS DATETIME; --// UPDATE BY AUN  2021/04/30
	DECLARE @TO_DATE AS DATETIME; -- // UPDATE BY AUN  2021/04/30
	
	SET @FROM_DATE = (SELECT CAST(@YEAR_MONTH + '01' AS DATE));
	--SET @TO_DATE = (SELECT DATEADD(d, -1, DATEADD(m, 1, @FROM_DATE))); // UPDATE BY AUN  2021/04/30
	SET @TO_DATE = (SELECT DATEADD(d, -1, FORMAT( DATEADD(m, 1, @FROM_DATE),'yyyy-MM-dd 20:00:00.000') ));

	SET @USD_RATE = (SELECT TOP 1 RATEFROMEXCHANGE FROM [APCSProDWH].[ONEWORLD].[RATE] WHERE CAST(EFFECTIVEFROM AS DATE) = @FROM_DATE AND CURRENCYFROMEXCHANGE = 'USD');
	SET @JPY_RATE = (SELECT TOP 1 RATEFROMEXCHANGE FROM [APCSProDWH].[ONEWORLD].[RATE] WHERE CAST(EFFECTIVEFROM AS DATE) = @FROM_DATE AND CURRENCYFROMEXCHANGE = 'JPY');
	
	IF @USD_RATE IS NULL
	BEGIN
		SET @USD_RATE = (SELECT TOP 1 RATEFROMEXCHANGE FROM [APCSProDWH].[ONEWORLD].[RATE] WHERE CURRENCYFROMEXCHANGE = 'USD' ORDER BY CAST(@YEAR_MONTH + '01' AS DATE) DESC);
	END

	IF @JPY_RATE IS NULL
	BEGIN
		SET @JPY_RATE = (SELECT TOP 1 RATEFROMEXCHANGE FROM [APCSProDWH].[ONEWORLD].[RATE] WHERE CURRENCYFROMEXCHANGE = 'JPY' ORDER BY CAST(@YEAR_MONTH + '01' AS DATE) DESC);
	END

	INSERT [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING] (
	   [year_month]
      ,[purchase_date]
      ,[invoice_no]
      ,[product_name]
      ,[quantity]
      ,[unit_prc_jpy]
      ,[unit_amount_jpy]
      ,[unit_prc_thb]
      ,[unit_amount_thb]
      ,[unit_prc_usd]
      ,[amount_usd]
      ,[tr_unit_prc]
      ,[tr_unit_amount]
      ,[currency]
      ,[unit]
      ,[location]
	  ,[rate_usd]
	  ,[rate_jpy]
      ,[created_by]
      ,[created_at]
	  ,[po_no])
	SELECT	@YEAR_MONTH,
			[RECORDS].[CREATED_AT],
			[ARRIVAL].[INVOICE_NO],
			[PROD].[NAME],
			[RECORDS].[QUANTITY],
			-- JPY --
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN 0
				WHEN 'JPY' THEN ROUND(ISNULL([INVOICES].ORGRECEIVINGUNITPRICE, 0), 4)
				WHEN 'USD' THEN 0
			END AS [UNIT_PRC_JPY],
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN 0
				WHEN 'JPY' THEN ISNULL([INVOICES].ORGRECEIVINGAMOUNT, 0)
				WHEN 'USD' THEN 0
			END AS [UNIT_AMOUNT_JPY],
			-- THB --
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN ROUND(ISNULL([INVOICES].ORGRECEIVINGUNITPRICE, 0), 4)
				WHEN 'JPY' THEN 0
				WHEN 'USD' THEN 0
			END AS [UNIT_PRC_THB],
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN ISNULL([INVOICES].ORGRECEIVINGAMOUNT, 0)
				WHEN 'JPY' THEN 0
				WHEN 'USD' THEN 0
			END AS [UNIT_AMOUNT_THB],
			-- USD --
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN 0
				WHEN 'JPY' THEN 0
				WHEN 'USD' THEN ROUND(ISNULL([INVOICES].ORGRECEIVINGUNITPRICE, 0), 4)
			END AS [UNIT_PRC_USD],
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN 0
				WHEN 'JPY' THEN 0
				WHEN 'USD' THEN ISNULL([INVOICES].ORGRECEIVINGAMOUNT, 0)
			END AS [UNIT_AMOUNT_USD],
			-- TR --
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN ISNULL([INVOICES].ORGRECEIVINGUNITPRICE, 0)
				WHEN 'JPY' THEN ISNULL([INVOICES].ORGRECEIVINGUNITPRICE, 0) * ISNULL(@JPY_RATE, 0)
				WHEN 'USD' THEN ISNULL([INVOICES].ORGRECEIVINGUNITPRICE, 0) * ISNULL(@USD_RATE, 0)
			END AS [TR_UNIT_PRC],
			CASE [ARRIVAL].[CURRENCY]
				WHEN 'THB' THEN ISNULL([INVOICES].ORGRECEIVINGAMOUNT, 0)
				WHEN 'JPY' THEN ISNULL([INVOICES].ORGRECEIVINGAMOUNT, 0) * ISNULL(@JPY_RATE, 0)
				WHEN 'USD' THEN ISNULL([INVOICES].ORGRECEIVINGAMOUNT, 0) * ISNULL(@USD_RATE, 0)
			END AS [TR_AMOUNT],
			[ARRIVAL].[CURRENCY],
			[UNIT].[DESCRIPTIONS],
			[LOC].[WH_CODE],
			@USD_RATE,
			@JPY_RATE,
			@USER_ID,
			GETDATE(),
			[ARRIVAL].PO_NO
	FROM [APCSProDB].[TRANS].[MATERIAL_RECORDS] [RECORDS]
		INNER JOIN [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS] [ARRIVAL] ON [RECORDS].MATERIAL_ID = [ARRIVAL].[MATERIAL_ID]
		INNER JOIN [APCSProDB].[TRANS].[MATERIALS] [MATL] ON [RECORDS].MATERIAL_ID = [MATL].ID
		INNER JOIN [APCSProDB].[MATERIAL].[PRODUCTIONS] [PROD] ON [RECORDS].MATERIAL_PRODUCTION_ID = [PROD].ID
		INNER JOIN [APCSProDB].[MATERIAL].[MATERIAL_CODES] [UNIT] ON [PROD].UNIT_CODE = [UNIT].CODE AND [UNIT].[GROUP] = 'package_unit'
		INNER JOIN [APCSProDB].[MATERIAL].[LOCATIONS] [LOC] ON [RECORDS].[LOCATION_ID] = [LOC].[ID]
		LEFT JOIN [APCSProDWH].[ONEWORLD].[INVOICE] [INVOICES] ON [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([ARRIVAL].[INVOICE_NO], '^a-z0-9') = [StoredProcedureDB].MATERIAL.FN_STRIPCHARACTERS([INVOICES].INVOICENO, '^a-z0-9')
			--AND [INVOICES].PONO = [ARRIVAL].PO_NO
			AND SUBSTRING([INVOICES].PONO, 1, LEN([ARRIVAL].PO_NO)) = [ARRIVAL].PO_NO
		INNER JOIN [APCSProDB].[TRANS].[DAYS] [DAYS] ON [DAYS].ID = [RECORDS].DAY_ID
		WHERE [RECORDS].RECORD_CLASS = '0' 
		AND [ARRIVAL].LOCATION_ID IN (SELECT ID FROM [APCSProDB].[MATERIAL].[LOCATIONS] WHERE WH_CODE IN ('QI900'))
		AND [RECORDS].LOCATION_ID IN (SELECT ID FROM [APCSProDB].[MATERIAL].[LOCATIONS] WHERE WH_CODE IN ('QI900'))
		--AND [PROD].CATEGORY_ID = (SELECT TOP 1 ID FROM [Material].[CATEGORIES] WHERE SHORT_NAME = '03')
		AND [ARRIVAL].RECORDED_AT BETWEEN @FROM_DATE AND @TO_DATE
		ORDER BY [RECORDS].ID;

	DELETE [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING_SUMMARY] WHERE [YEAR_MONTH] = @YEAR_MONTH;

	INSERT [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING_SUMMARY] (
	   [YEAR_MONTH]
      ,[PURCHASE_DATE]
      ,[INVOICE_NO]
      ,[PRODUCT_NAME]
      ,[UNIT]
      ,[QUANTITY]
      ,[UNIT_AMOUNT_JPY]
      ,[AMOUNT_USD]
      ,[UNIT_AMOUNT_THB]
      ,[RATE_USD]
      ,[RATE_JPY])
	SELECT 
		  [YEAR_MONTH]
		  ,CONVERT(DATE, [PURCHASE_DATE]) AS [PURCHASE_DATE]
		  ,[INVOICE_NO]
		  ,[PRODUCT_NAME]
		  ,[UNIT]
		  ,SUM([QUANTITY]) AS [QUANTITY]
		  ,[UNIT_AMOUNT_JPY]
		  ,[AMOUNT_USD] AS [AMOUNT_USD]
		  ,[UNIT_AMOUNT_THB]
		  ,[RATE_USD]
		  ,[RATE_JPY]
	  FROM [APCSProDB].[TRANS].[RPT_FRAME_MATERIAL_RECEIVING] WHERE [YEAR_MONTH] = @YEAR_MONTH
	  GROUP BY 
		  [YEAR_MONTH]
		  ,CONVERT(DATE, [PURCHASE_DATE])
		  ,[INVOICE_NO]
		  ,[PRODUCT_NAME]
		  ,[CURRENCY]
		  ,[UNIT]
		  ,[UNIT_AMOUNT_JPY]
		  ,[AMOUNT_USD]
		  ,[UNIT_AMOUNT_THB]
		  ,[RATE_USD]
		  ,[RATE_JPY]
		  ,[PO_NO]
	  ORDER BY [PRODUCT_NAME];
END;

-- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  -- ********************** --  

--EXEC [trans].[sp_rpt_rcv_frame_process] '201910', 2, 1