
CREATE PROCEDURE [trans].[sp_rpt_ledger_compute]
@YEAR_MONTH INTEGER,
@LOCATION_ID INT,
@USER_ID INT
AS
BEGIN
	UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		SET AVG_UNIT_PRC = ROUND((ISNULL(MONTH_BEGIN_AMT, 0) + ISNULL(REC1_AMT, 0) + ISNULL(REC2_AMT, 0) + ISNULL(REC3_AMT, 0)) 
			/ (ISNULL(MONTH_BEGIN_QTY, 0) + ISNULL(REC1_QTY, 0) + ISNULL(REC2_QTY, 0) + ISNULL(REC3_QTY, 0)), 4)
	WHERE [YEAR_MONTH] = @YEAR_MONTH
	AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))
	AND (ISNULL(MONTH_BEGIN_QTY, 0) + ISNULL(REC1_QTY, 0) + ISNULL(REC2_QTY, 0)) > 0;	

	-- Tun 2020/01/29 
	--UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
	--	-- 20200106 -- RAPEPHATRA -- SET SERV2_AMT = ISNULL(SERV2_QTY, 0) * ISNULL(AVG_UNIT_PRC, 0),
	--	SET SERV2_AMT = ROUND(ISNULL(SERV2_QTY, 0) * ISNULL(AVG_UNIT_PRC, 0), 2),
	--	WH_INV_AMT = ISNULL(WH_INV_QTY, 0) * ISNULL(AVG_UNIT_PRC, 0)
	--WHERE [YEAR_MONTH] = @YEAR_MONTH
	--AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))
	
	-- แก้ให้บวก in_process_qty ก่อน * avg_unit_price 2020/01/29
	UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		-- 20200106 -- RAPEPHATRA -- SET SERV2_AMT = ISNULL(SERV2_QTY, 0) * ISNULL(AVG_UNIT_PRC, 0),
		SET SERV2_AMT = ROUND(ISNULL(SERV2_QTY, 0) * ISNULL(AVG_UNIT_PRC, 0), 2),
		WH_INV_AMT = ROUND((ISNULL(WH_INV_QTY, 0) + ISNULL(IN_PROCESS_QTY,0)) * ISNULL(AVG_UNIT_PRC, 0),2)
	WHERE [YEAR_MONTH] = @YEAR_MONTH
	AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))
	 


	
	UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		SET [MONTH_END_QTY] = (ISNULL([MONTH_BEGIN_QTY], 0) + ISNULL([REC1_QTY], 0) + ISNULL([REC2_QTY], 0) + ISNULL([REC3_QTY], 0)) - (ISNULL([SERV1_QTY], 0) + ISNULL([SERV2_QTY], 0) + ISNULL([defect_qty], 0)),
		[MONTH_END_AMT] = ROUND( ((ISNULL([MONTH_BEGIN_QTY], 0) + ISNULL([REC1_QTY], 0) + ISNULL([REC2_QTY], 0) + ISNULL([REC3_QTY], 0)) - (ISNULL([SERV1_QTY], 0) + ISNULL([SERV2_QTY], 0)) + ISNULL([defect_qty], 0)) * ISNULL(AVG_UNIT_PRC, 0) ,2)
	WHERE [YEAR_MONTH] = @YEAR_MONTH
	AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))
	
	

	--UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
	--	SET DIFF_QTY = [MONTH_END_QTY] - [WH_INV_QTY],
	--	DIFF_AMT = [MONTH_END_AMT] - [WH_INV_AMT]
	--WHERE [YEAR_MONTH] = @YEAR_MONTH
	--AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))

	--- แก้ให้บวก [WH_INV_QTY] + in_process_qty ก่อนลบ [MONTH_END_QTY]  2020/01/29
	UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		SET DIFF_QTY = [MONTH_END_QTY] - ([WH_INV_QTY] + ISNULL([IN_PROCESS_QTY],0)),
		DIFF_AMT = [MONTH_END_AMT] - [WH_INV_AMT]
	WHERE [YEAR_MONTH] = @YEAR_MONTH
	AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))

		
	UPDATE [APCSProDB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		SET SERV1_AMT = ISNULL(month_begin_amt, 0) + ISNULL(rec1_amt, 0) + ISNULL(rec2_amt, 0) + ISNULL(rec3_amt, 0) - ISNULL(serv2_amt, 0) - ISNULL(defect_amt, 0) - ISNULL(defect_amt, 0) - ISNULL(month_end_amt, 0),
		defect_qty = ISNULL(defect_qty, 0),
		defect_amt = ISNULL(defect_amt, 0)
	WHERE [YEAR_MONTH] = @YEAR_MONTH
	AND LOCATION_ID IN (SELECT ID FROM [APCSProDB].MATERIAL.LOCATIONS WHERE WH_CODE IN ('QI900', 'QI999'))

	UPDATE [APCSPRODB].[TRANS].[MATERIAL_LEDGER_PROCESS]
		SET CATEGORY_SHORT_NAME = (SELECT TOP 1 CATEGORY_ID FROM [APCSPRODB].MATERIAL.PRODUCTIONS WHERE [NAME] = PRODUCT_NAME)
END;
