CREATE procedure trans.sp_rollback_mat_transaction
@TRANSACTION_ID AS INT
AS
BEGIN
	DECLARE @RECORD_CLASS AS INT
	DECLARE @OUT_GOING_ID AS INT
	DECLARE @FROM_LOCATION_ID AS INT
	SET @RECORD_CLASS = (SELECT RECORD_CLASS FROM [APCSPRODB].TRANS.MATERIAL_RECORDS WHERE ID = @TRANSACTION_ID);
	
	IF @RECORD_CLASS = 2
	BEGIN
		SET @OUT_GOING_ID = (SELECT MATERIAL_OUTGOINGS_ID 
			FROM [APCSPRODB].TRANS.MATERIAL_OUTGOING_ITEMS WHERE RECORD_ID = @TRANSACTION_ID);

		SET @FROM_LOCATION_ID = (SELECT FROM_LOCATION_ID 
			FROM [APCSPRODB].TRANS.MATERIAL_OUTGOINGS WHERE ID = @OUT_GOING_ID);

		UPDATE [APCSPRODB].TRANS.MATERIALS SET LOCATION_ID = @FROM_LOCATION_ID
			WHERE ID IN (SELECT MATERIAL_ID 
				FROM [APCSPRODB].TRANS.MATERIAL_OUTGOING_ITEMS WHERE MATERIAL_OUTGOINGS_ID = @OUT_GOING_ID);

		DELETE [APCSPRODB].TRANS.MATERIAL_RECORDS WHERE ID IN (
			SELECT RECORD_ID 
				FROM [APCSPRODB].TRANS.MATERIAL_OUTGOING_ITEMS WHERE MATERIAL_OUTGOINGS_ID = @OUT_GOING_ID);

		DELETE [APCSPRODB].TRANS.MATERIAL_OUTGOING_ITEMS WHERE MATERIAL_OUTGOINGS_ID = @OUT_GOING_ID;

		DELETE FROM [APCSPRODB].TRANS.MATERIAL_OUTGOINGS WHERE ID = @OUT_GOING_ID;
	END
END