

CREATE PROCEDURE [trans].[sp_sync_id]
AS
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN
	BEGIN TRAN
		DECLARE @MAXID_LOCATIONS INT
		SET @MAXID_LOCATIONS = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[MATERIAL].[LOCATIONS]), 1)
		UPDATE [APCSProDB].[MATERIAL].[NUMBERS] SET [ID] = @MAXID_LOCATIONS WHERE [NAME] = 'locations.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[MATERIAL].[NUMBERS] ([NAME], [ID]) VALUES ('locations.id', @MAXID_LOCATIONS)
		END
	COMMIT TRAN

	BEGIN TRAN
		DECLARE @MAXID_CONTROLS INT
		SET @MAXID_CONTROLS = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[MATERIAL].[CONTROLS]), 1)
		UPDATE [APCSProDB].[MATERIAL].[NUMBERS] SET [ID] = @MAXID_CONTROLS WHERE [NAME] = 'controls.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[MATERIAL].[NUMBERS] ([NAME], [ID]) VALUES ('controls.id', @MAXID_CONTROLS)
		END
	COMMIT TRAN

	BEGIN TRAN
		DECLARE @MAXID_CATEGORIES INT
		SET @MAXID_CATEGORIES = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[MATERIAL].[CATEGORIES]), 1)
		UPDATE [APCSProDB].[MATERIAL].[NUMBERS] SET [ID] = @MAXID_CATEGORIES WHERE [NAME] = 'categories.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[MATERIAL].[NUMBERS] ([NAME], [ID]) VALUES ('categories.id', @MAXID_CATEGORIES)
		END
	COMMIT TRAN

	BEGIN TRAN
		DECLARE @MAXID_PRODUCTIONS INT
		SET @MAXID_PRODUCTIONS = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[MATERIAL].[PRODUCTIONS]), 1)
		UPDATE [APCSProDB].[MATERIAL].[NUMBERS] SET [ID] = @MAXID_PRODUCTIONS WHERE [NAME] = 'productions.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[MATERIAL].[NUMBERS] ([NAME], [ID]) VALUES ('productions.id', @MAXID_PRODUCTIONS)
		END
	COMMIT TRAN

	BEGIN TRAN
		DECLARE @MAXID_MATERIALS INT
		SET @MAXID_MATERIALS = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[TRANS].[MATERIALS]), 1)
		UPDATE [APCSProDB].[trans].[NUMBERS] SET [ID] = @MAXID_MATERIALS WHERE [NAME] = 'materials.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[trans].[NUMBERS] ([NAME], [ID]) VALUES ('materials.id', @MAXID_MATERIALS)
		END
	COMMIT TRAN

	BEGIN TRAN
		DECLARE @MAXID_MATERIAL_ARRIVAL_RECORDS INT
		SET @MAXID_MATERIAL_ARRIVAL_RECORDS = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[TRANS].[MATERIAL_ARRIVAL_RECORDS]), 1)
		UPDATE [APCSProDB].[trans].[NUMBERS] SET [ID] = @MAXID_MATERIAL_ARRIVAL_RECORDS WHERE [NAME] = 'material_arrival_records.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[trans].[NUMBERS] ([NAME], [ID]) VALUES ('material_arrival_records.id', @MAXID_MATERIAL_ARRIVAL_RECORDS)
		END
	COMMIT TRAN
	
	BEGIN TRAN
		DECLARE @MAXID_MATERIAL_RECORDS INT
		SET @MAXID_MATERIAL_RECORDS = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[TRANS].[MATERIAL_RECORDS]), 1)
		UPDATE [APCSProDB].[trans].[NUMBERS] SET [ID] = @MAXID_MATERIAL_RECORDS WHERE [NAME] = 'material_records.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[trans].[NUMBERS] ([NAME], [ID]) VALUES ('material_records.id', @MAXID_MATERIAL_RECORDS)
		END
	COMMIT TRAN

	BEGIN TRAN
		DECLARE @MAXID_MATERIAL_INVENTORY_FILE INT
		SET @MAXID_MATERIAL_INVENTORY_FILE = ISNULL((SELECT MAX([ID]) FROM [APCSProDB].[TRANS].[MATERIAL_INVENTORY_FILE]), 1)
		UPDATE [APCSProDB].[trans].[NUMBERS] SET [ID] = @MAXID_MATERIAL_INVENTORY_FILE WHERE [NAME] = 'material_inventory_file.id';
		IF @@ROWCOUNT = 0
		BEGIN
			INSERT [APCSProDB].[trans].[NUMBERS] ([NAME], [ID]) VALUES ('material_inventory_file.id', @MAXID_MATERIAL_INVENTORY_FILE)
		END
	COMMIT TRAN
END