
CREATE PROCEDURE [trans].[sp_update_receiving_invoice]
@ID INT,
@INVOICE VARCHAR(200)
AS
BEGIN
	UPDATE [APCSProDB].[TRANS].[MATERIAL_RECEIVING_RECORDS] SET INVOICE_NUMBER  = @INVOICE WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID;
	UPDATE [APCSProDB].[TRANS].MATERIAL_ARRIVAL_RECORDS SET INVOICE_NO = @INVOICE 
		WHERE MATERIAL_ID IN (SELECT MATERIAL_ID FROM [APCSProDB].[TRANS].[MATERIAL_RECEIVING_RECORDS] WHERE MATERIAL_RECEIVING_PROCESS_ID = @ID);
END