-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [atom].[sp_set_history_records]	
	-- Add the parameters for the stored procedure here
	@LotIdTable lot_tomson3 READONLY,
	@user_id INT,
	@table_name VARCHAR(255)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	IF (@table_name = 'surpluses')
	BEGIN
		INSERT INTO [APCSProDB].[trans].[surpluse_records]
			( [recorded_at]
			, [operated_by]
			, [record_class]
			, [surpluse_id]
			, [lot_id]
			, [pcs]
			, [serial_no]
			, [in_stock]
			, [location_id]
			, [acc_location_id]
			, [reprint_count]
			, [created_at]
			, [created_by]
			, [updated_at]
			, [updated_by]
			, [product_code]
			, [qc_instruction]
			, [mark_no]
			, [original_lot_id]
			, [machine_id]
			, [user_code]
			, [product_control_class]
			, [product_class]
			, [production_class]
			, [rank_no]
			, [hinsyu_class]
			, [label_class]
			, [transfer_flag]
			, [transfer_pcs]
			, [stock_class]
			, [is_ability]
			, [comment] )
		SELECT GETDATE() AS [recorded_at]
			, @user_id AS [operated_by]
			, 2 AS [record_class]
			, [surpluses].[id] AS [surpluse_id]
			, [surpluses].[lot_id]
			, [surpluses].[pcs]
			, [surpluses].[serial_no]
			, [surpluses].[in_stock]
			, [surpluses].[location_id]
			, [surpluses].[acc_location_id]
			, [surpluses].[reprint_count]
			, [surpluses].[created_at]
			, [surpluses].[created_by]
			, [surpluses].[updated_at]
			, [surpluses].[updated_by]
			, [surpluses].[pdcd] AS [product_code]
			, [surpluses].[qc_instruction]
			, [surpluses].[mark_no]
			, [surpluses].[original_lot_id]
			, [surpluses].[machine_id]
			, [surpluses].[user_code]
			, [surpluses].[product_control_class]
			, [surpluses].[product_class]
			, [surpluses].[production_class]
			, [surpluses].[rank_no]
			, [surpluses].[hinsyu_class]
			, [surpluses].[label_class]
			, [surpluses].[transfer_flag]
			, [surpluses].[transfer_pcs]
			, [surpluses].[stock_class]
			, [surpluses].[is_ability]
			, [surpluses].[comment]
		FROM (
			SELECT [lot_id], ROW_NUMBER() OVER (ORDER BY ( SELECT 1 )) AS [row]
			FROM @LotIdTable
		) AS [table_lot]
		INNER JOIN [APCSProDB].[trans].[lots] ON [table_lot].[lot_id] = [lots].[id]
		INNER JOIN [APCSProDB].[trans].[surpluses] ON [lots].[id] = [surpluses].[lot_id]
		ORDER BY [table_lot].[row] ASC;
	END
	ELSE IF (@table_name = 'label_issue_records')
	BEGIN
		INSERT INTO [APCSProDB].[trans].[label_issue_records_hist]
			( [label_issue_id]
			, [recorded_at]
			, [record_class]
			, [operated_by]
			, [type_of_label]
			, [lot_no]
			, [customer_device]
			, [rohm_model_name]
			, [qty]
			, [barcode_lotno]
			, [tomson_box]
			, [tomson_3]
			, [box_type]
			, [barcode_bottom]
			, [mno_std]
			, [std_qty_before]
			, [mno_hasuu]
			, [hasuu_qty_before]
			, [no_reel]
			, [qrcode_detail]
			, [type_label_laterat]
			, [mno_std_laterat]
			, [mno_hasuu_laterat]
			, [barcode_device_detail]
			, [op_no]
			, [op_name]
			, [seq]
			, [ip_address]
			, [msl_label]
			, [floor_life]
			, [ppbt]
			, [re_comment]
			, [version]
			, [is_logo]
			, [mc_name]
			, [barcode_1_mod]
			, [barcode_2_mod]
			, [seal]
			, [create_at]
			, [create_by]
			, [update_at]
			, [update_by] )
		SELECT [label_issue_records].[id] AS [label_issue_id]
			, GETDATE() AS [recorded_at]
			, 2 AS [record_class]
			, @user_id AS [operated_by]
			, [label_issue_records].[type_of_label]
			, [label_issue_records].[lot_no]
			, [label_issue_records].[customer_device]
			, [label_issue_records].[rohm_model_name]
			, [label_issue_records].[qty]
			, [label_issue_records].[barcode_lotno]
			, [label_issue_records].[tomson_box]
			, [label_issue_records].[tomson_3]
			, [label_issue_records].[box_type]
			, [label_issue_records].[barcode_bottom]
			, [label_issue_records].[mno_std]
			, [label_issue_records].[std_qty_before]
			, [label_issue_records].[mno_hasuu]
			, [label_issue_records].[hasuu_qty_before]
			, [label_issue_records].[no_reel]
			, [label_issue_records].[qrcode_detail]
			, [label_issue_records].[type_label_laterat]
			, [label_issue_records].[mno_std_laterat]
			, [label_issue_records].[mno_hasuu_laterat]
			, [label_issue_records].[barcode_device_detail]
			, [label_issue_records].[op_no]
			, [label_issue_records].[op_name]
			, [label_issue_records].[seq]
			, [label_issue_records].[ip_address]
			, [label_issue_records].[msl_label]
			, [label_issue_records].[floor_life]
			, [label_issue_records].[ppbt]
			, [label_issue_records].[re_comment]
			, [label_issue_records].[version] 
			, [label_issue_records].[is_logo]
			, [label_issue_records].[mc_name]
			, [label_issue_records].[barcode_1_mod]
			, [label_issue_records].[barcode_2_mod]
			, [label_issue_records].[seal]
			, [label_issue_records].[create_at]
			, [label_issue_records].[create_by]
			, [label_issue_records].[update_at]
			, [label_issue_records].[update_by]
		FROM (
			SELECT [lot_id], ROW_NUMBER() OVER (ORDER BY ( SELECT 1 )) AS [row]
			FROM @LotIdTable
		) AS [table_lot]
		INNER JOIN [APCSProDB].[trans].[lots] ON [table_lot].[lot_id] = [lots].[id]
		INNER JOIN [APCSProDB].[trans].[label_issue_records] ON [label_issue_records].[lot_no] = [lots].[lot_no]
		ORDER BY [table_lot].[row] ASC, [label_issue_records].[type_of_label] ASC;
	END
END
