CREATE TABLE [dbo].[aaa_backup] (
    [date_value]              DATE          NOT NULL,
    [package_group]           VARCHAR (50)  NOT NULL,
    [package]                 VARCHAR (50)  NOT NULL,
    [process]                 VARCHAR (50)  NOT NULL,
    [job]                     VARCHAR (50)  NOT NULL,
    [lot_type]                VARCHAR (50)  NOT NULL,
    [normal]                  INT           NULL,
    [normal_pcs]              INT           NULL,
    [delay]                   INT           NULL,
    [delay_pcs]               INT           NULL,
    [order_delay]             INT           NULL,
    [order_delay_pcs]         INT           NULL,
    [order_delay_hold]        INT           NULL,
    [order_delay_hold_pcs]    INT           NULL,
    [hold]                    INT           NULL,
    [hold_pcs]                INT           NULL,
    [total]                   INT           NULL,
    [total_pcs]               INT           NULL,
    [machine]                 INT           NULL,
    [machine_pcs]             INT           NULL,
    [actual_result]           INT           NULL,
    [actual_result_pcs]       INT           NULL,
    [yesterday_result]        INT           NULL,
    [yesterday_result_pcs]    INT           NULL,
    [seq_no]                  INT           NULL,
    [processing_time]         INT           NULL,
    [wip_time]                INT           NULL,
    [today_input]             INT           NULL,
    [today_input_pcs]         INT           NULL,
    [today_output]            INT           NULL,
    [today_output_pcs]        INT           NULL,
    [specialflow]             INT           NULL,
    [specialflow_pcs]         INT           NULL,
    [order_delay_special]     INT           NULL,
    [order_delay_special_pcs] INT           NULL,
    [device]                  VARCHAR (50)  NULL,
    [factory]                 NVARCHAR (5)  NULL,
    [hq]                      NVARCHAR (10) NULL,
    [division]                NVARCHAR (50) NULL,
    [product_family]          NVARCHAR (50) NULL,
    [partition_no]            INT           NULL
);

